### ISSUE TITLE
Proofread

### ISSUE THREAD

**Issue by regisb** [regisb/openedx-docker#1]
Ping @gsong @Omarithawi @WolfieZero :)

This is a work-in-progress that stems from my [install-from-scratch manual](https://github.com/regisb/openedx-install). The idea is to launch a minimal, docker-based LMS. 

After running `docker-compose up --build` you should have a working lms listening on http://myopenedx.com. You will have to patch your `/etc/hosts` file to access it.

In order to disable migrations and assets generation, just modifiy the environment variables in `docker-compose.yml`.

Since I know close to nothing about Docker, I would really appreciate it if you could give some pointers on good practices and any stupid mistake I might have made.

**Comment by WolfieZero** [comment]
I don't know much about docker either other than some very bad implementations of it! But I can see the benefit for using it with something like edX.

Will look at this ASAP :)

**Comment by OmarIthawi** [comment]
Pong @regisb!

Review is in progress...

**Comment by OmarIthawi** [comment]
It's been difficult to start this stack.

I'd like to suggest that you take a look at my previous attempt:

 - https://github.com/Edraak/edx-docker-devstack

It is also written from scratch (i.e. no ansible). However that one is more focused toward dev., not sure about this repo.


Mine is definitely not complete and we can merge efforts. However, mine features few different tradeoffs:

 - Separate build/run configurations
 - Which results in quick `docker-compose up` time
 - No IP lookup, ports are exposed to localhost
 - Code sync. Copy the out of the container for the dev start working!

**Comment by regisb** [comment]
Hey @OmarIthawi thanks a lot for working on this! (on a Sunday)
Most of the time is taken in 1) git clone 2) migrations 3) assets collection. Step 1 will be reduced once images are uploaded to hub.docker.com. As for steps 2 and 3, I don't think I could really accelerate that without moving data to the containers.

There's a lot to borrow from your Dockerfiles; will *definitely* integrate some stuff.

I noticed that there is some complexity getting syslog to work. I managed to solve that by setting ` dev_env=True` in the `LOGGING` setting: https://github.com/regisb/openedx-docker/blob/master/lms/production.py Did you know about that trick?

**Comment by OmarIthawi** [comment]
> Hey @OmarIthawi thanks a lot for working on this! (on a Sunday)
You're welcome 😃 

FYI our Sunday is like your Monday. It's the first business day of the week 😄

> I noticed that there is some complexity getting syslog to work. I managed to solve that by setting dev_env=True in the LOGGING setting: https://github.com/regisb/openedx-docker/blob/master/lms/production.py Did you know about that trick?

It's been a long time. Perhaps I chose not to change the platform as much as possible. But looks like your approach is better.

**Comment by gsong** [comment]
Love seeing the collaboration here. I haven't had time to pick up on this yet, but be sure it's on my radar.

**Comment by regisb** [comment]
This issue can be closed, now that the 1-click install is working.
