### ISSUE TITLE
How can I change the data on number of login failures until someone is locked out?

### ISSUE THREAD

**Issue by frohro** [regisb/openedx-docker#100]
PLEASE PLEASE PLEASE READ THIS AND FOLLOW THE INSTRUCTIONS WHEN OPENING A NEW ISSUE

## Steps to reproduce

Include the exact command that you are running and that is causing an error. In case of a web error, include the URL of the page that is causing the error.

## Unexpected behavior

Include the full, exact output from the command that is causing your issue. Also include relevant error logs; for instance, to debug the LMS take a look at the files in `data/lms/logs`.

## Additional info (IMPORTANT)

Include the output of the `make info` command.

**Comment by frohro** [comment]
I have students who forgot their passwords and tried several they use, but then get locked out for a time.  I would like to change the number of attempts and/or the time.  This web page tells how to do it, but it is from 2014, and I'm not quite sure how to follow the instructions here in 2018.  :-)

https://github.com/edx/edx-platform/wiki/Optional-Account-lockout-after-excessive-login-failures

Thanks for the help!

**Comment by regisb** [comment]
If you want to disable the optional account lockout, you need to add `"ENABLE_MAX_FAILED_LOGIN_ATTEMPTS": false` to the "FEATURES" entry in `config/lms.env.json`.

**Comment by frohro** [comment]
I think you meant config/openedx/lms.env.json .
Thanks for the help!
Rob
