### ISSUE TITLE
Question: Why is themes in data?

### ISSUE THREAD

**Issue by frob** [regisb/openedx-docker#106]
It seems like everything is in data? For the theme especially `/src` seems like a better place. Is this an EdX convention?

**Comment by regisb** [comment]
Do you mean, on the host or in the container? The idea is to mount the themes folder from the host to the container, and it's simpler if we only have to mount a single folder.

Does that answer your question?

**Comment by frob** [comment]
Nah, I was asking why do you favor the directory structure for the project where `themes` is in the `data` directory. Most projects would have the working source in the `src` directory. I know it works either way, I just find it a little confusing and thought others might as well.

Up till now everything in `data` is strictly data and not source code. Even the requirements are under `openedx/requirements`.

**Comment by regisb** [comment]
I get your point. In the future, themes will not be working this way anymore: they will be copied from openedx/themes (outside of data/) to the container (in /openedx/themes) at build time. You can take a look at the [assets branch](https://github.com/regisb/openedx-docker/pull/102).
