### ISSUE TITLE
404 on course page

### ISSUE THREAD

**Issue by alincalinciuc** [regisb/openedx-docker#11]
After adding the demo project if you try to go to the course page you get a 404 on 
http://edx.domain.com/courses/course-v1:edX+DemoX+Demo_Course/about .

**Comment by alincalinciuc** [comment]
Same thing happens with a brand new created course. 
I've also tried http://admin.edx.domain.com/maintenance/force_publish_course it but nothing changes.

**Comment by regisb** [comment]
Hi! Thanks for taking the time to report this.

As per my previous recommendation, did you update the `openedx-docker` repo? The CMS was initially pointing to a different Mongodb collection than the LMS, making the courses created by the CMS unfindable by the LMS. You need to update the repo *and then* create a new course.

Did you log in to a user account in the LMS ? Anonymous users do not have the permission to view "about" pages of newly created courses.

**Comment by alincalinciuc** [comment]
Hi Régis,
I did all of that, I've `rm -rf data/*` , updated the repo with your last commit (189ea3e7dc9695f7287f85202f57746728b42f5c) and then `make all` . 
Same result, I always receive a 404 page, no matter if I create a new project or I import the demo one.
I've tried the Force Publish functionality but with no success.
Some help would be really appreciated.
Best regards,
Alin

**Comment by regisb** [comment]
1) Can you confirm you were logged in with a staff account in the LMS?
2) Did you try creating a course in the CMS? Can you then see its "about" page in the LMS?

**Comment by regisb** [comment]
Hi @alincalinciuc, did you manage to solve this problem?

**Comment by dannielarriola** [comment]
Hi, I have the same issue. It works with staff user, but not with the unregistered user

**Comment by dannielarriola** [comment]
I found a solution [here](https://www.dangtrinh.com/2017/10/open-edx-course-about-page-not-found-on.html)

**Comment by regisb** [comment]
I am currently investigating this issue, but it's really difficult to diagnose. It seems the bug lies deep inside the modulestore, which is a thorny part of the codebase.
@dannielarriola : I am pretty sure the solution you proposed (changing `PREVIEW_LMS_BASE`) does not work.
@alincalinciuc : "It seems to work if I add the user created on LMS as Staff on the project." Can you explain what you did exactly?

**Comment by dannielarriola** [comment]
Hi @regisb 
Why you say that not work?. Maybe isn't the main problem but it's work perfectly.
See [this](http://edx.develapp.ml/) and [this](http://mom-home.com/). The fist one does not work, and the second with de PREVIEW_LMS_BASE change works great.
Sorry for my english

**Comment by regisb** [comment]
@dannielarriola you were absolutely right! in the latest release I changed the default preview path to preview.LMS_BASE. Thanks a lot for the tip!
