### ISSUE TITLE
What's the difference between this repo and and openfun/fun-platform

### ISSUE THREAD

**Issue by natea** [regisb/openedx-docker#12]
They seem to have the same objectives?
https://github.com/openfun/fun-platform

**Comment by regisb** [comment]
Yes, these two projects are quite similar. `openedx-docker` served as an inspiration to @sampaccoud to containerize the FUN architecture for development. Thus, fun-platform is development-oriented (while openedx-docker focuses on production-ready containers) and it was designed to run FUN, which is an extra layer on top of Open edX (to simplify).

**Comment by sampaccoud** [comment]
We had second thoughts on `fun-platform` being a swiss knife and "designed for FUN". We have started a new separate project to automate deployments to Openshift and `fun-platform` will now only be responsible for building docker images of edx-platform in different flavors and pushing them to docker hub.

Another way to say it is that `fun-platform` will only do what we think should be integrated in the `edx-platform` repository. We hope edX or the community will soon move to Docker and build good Docker images so we could retire `fun-platform`.
