### ISSUE TITLE
Developer 'make lms' not working;  recipe for target 'lms' failed

### ISSUE THREAD

**Issue by gmsk19** [regisb/openedx-docker#18]
Dear Regis, 
              I have been trying out to build openedx with the pull request patch merged today. I am trying out the commands listed under development section.
Everything works till make migrate. **But if try to call 'make lms' or 'make cms', there is an error. Below is the stack trace.** 

Note: I only got to this section now(due to slow internet/computer), otherwise I would have reported yesterday itself before the patch was merged in to the master branch.

**Stacktrace**

docker-compose run --rm -e USERID="$(id -u)" -e SETTINGS=development --volume="/home/rudra/Desktop/iks_workspace/openedx/edx-platform:/openedx/edx-platform" -p 8000:8000 lms bash
Run a one-off command on a service.

For example:

    $ docker-compose run web python manage.py shell

By default, linked services will be started, unless they are already
running. If you do not want to start linked services, use
`docker-compose run --no-deps SERVICE COMMAND [ARGS...]`.

Usage: run [options] [-p PORT...] [-e KEY=VAL...] SERVICE [COMMAND] [ARGS...]

Options:
    -d                    Detached mode: Run container in the background, print
                          new container name.
    --name NAME           Assign a name to the container
    --entrypoint CMD      Override the entrypoint of the image.
    -e KEY=VAL            Set an environment variable (can be used multiple times)
    -u, --user=""         Run as specified username or uid
    --no-deps             Don't start linked services.
    --rm                  Remove container after run. Ignored in detached mode.
    -p, --publish=[]      Publish a container's port(s) to the host
    --service-ports       Run command with the service's ports enabled and mapped
                          to the host.
    -T                    Disable pseudo-tty allocation. By default `docker-compose run`
                          allocates a TTY.
    -w, --workdir=""      Working directory inside the container
Makefile:57: recipe for target 'lms' failed
make: *** [lms] Error 1

**Comment by regisb** [comment]
Hi @gmsk19, thanks for taking the time to open this issue! What are your docker and docker-compose versions?

Also, can you try to update to the latest master version? I have patched the pull request between the moment I sent you the link to the PR and the merge.

**Comment by gmsk19** [comment]
The Docker Version is 1.13.1
The docker-compose versions is 1.8.0
The Following were the commands I issued in sequence:

make configure
make build
make migrate
**make lms**
It fails after I issue 'make lms '

**Comment by regisb** [comment]
I suspect you need to upgrade to a ore recent version of docker/docker-compose. FYI, here's what I have on my machine:

```
$ docker --version
Docker version 18.03.0-ce, build 0520e24
$ docker-compose  --version
docker-compose version 1.19.0, build 9e633ef
```

**Comment by gmsk19** [comment]
Regis,
      as per your suggestions, I have upgraded to latest versions of docker and docker compose.They stand at 18.0.3 and 1.21.0 respectively. The command **'make lms'** did work, however I still cannot access the lms or cms site at localhost:8000, localhost:8001. 
I have decided to start over again afresh, will fresh pull from the master branch, starting with make configure. 
Will revert with the results once done.

**Comment by gmsk19** [comment]
Update on the Progress.
I went past the 'make lms' command. Then in the shell i executed **paver lms**
There were several dependency errors. I had to install python-gdmb and python-tk(using apt).
I also had to upgrade the version of nlkt(using pip uninstall nlkt, pip install --upgrade nlkt).
Then has to install pysqlite(and libsqlite3-dev).

Now I have hit upon the following error:

--> pavelib.assets.compile_coffeescript
node_modules/.bin/coffee --compile `find /openedx/edx-platform/lms /openedx/edx-platform/cms /openedx/edx-platform/common -type f -name "*.coffee"`
---> pavelib.assets.webpack
python manage.py lms --settings=devstack print_setting STATIC_ROOT 2>/dev/null


Build failed running pavelib.servers.lms: Subprocess return code: 1

**Comment by regisb** [comment]
1. What version of edx-platform are you running? You can get the git sha1 by running `git log -1` from inside the repository.
2. I see that you are using the `devstack` settings. Is that your intention? Did you modify the default devstack.py file?
3. The error message states that the command `python manage.py lms --settings=devstack print_setting STATIC_ROOT` fails. Please run this command from inside the container and post the error here.

**Comment by gmsk19** [comment]
Agree on the 4th point. Thank you for the queries. Below are my answers, followed by a different error stack-trace i am getting now.

1. ginkgo master

New Error Stacktrace:

root@23df1de26922:/openedx/edx-platform# paver lms --settings=development
---> pavelib.servers.lms
---> pavelib.prereqs.install_prereqs
---> pavelib.prereqs.install_node_prereqs
Node prereqs unchanged, skipping...
---> pavelib.prereqs.install_python_prereqs
---> pavelib.prereqs.uninstall_python_packages
Python uninstalls unchanged, skipping...
Python prereqs unchanged, skipping...
pip freeze > /openedx/edx-platform/test_root/log/pip_freeze.log
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
---> pavelib.assets.update_assets
xmodule_assets common/static/xmodule
Traceback (most recent call last):
  File "/usr/local/bin/xmodule_assets", line 11, in <module>
    load_entry_point('XModule', 'console_scripts', 'xmodule_assets')()
  File "/openedx/edx-platform/common/lib/xmodule/xmodule/static_content.py", line 207, in main
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/openedx/edx-platform/openedx/core/djangoapps/video_config/models.py", line 6, in <module>
    from opaque_keys.edx.django.models import CourseKeyField
ImportError: No module named django.models


Captured Task Output:
---------------------

---> pavelib.servers.lms
---> pavelib.prereqs.install_prereqs
---> pavelib.prereqs.install_node_prereqs
---> pavelib.prereqs.install_python_prereqs
---> pavelib.prereqs.uninstall_python_packages
pip freeze > /openedx/edx-platform/test_root/log/pip_freeze.log
---> pavelib.assets.update_assets
xmodule_assets common/static/xmodule

Build failed running pavelib.servers.lms: Subprocess return code: 1

**Comment by regisb** [comment]
Your container does not seed to have all the requirements installed. Are you sure you correctly built the image? You can make sure of that by running `make build` on the host.
Also, Github issues are not really convenient for such back and forth exchanges. I'll be on IRC for the next hour or so. I'm regisb on #freenode. Feel free to ping me.

**Comment by regisb** [comment]
Please run on the host:

    make lms

And then in the container:

    python manage.py lms --settings=development print_setting STATIC_ROOT

What is the error message?

**Comment by gmsk19** [comment]
After running the following command in Container:

python manage.py lms --settings=development print_setting STATIC_ROOT

I get the following error message:

Traceback (most recent call last):
  File "manage.py", line 117, in <module>
    startup = importlib.import_module(edx_args.startup)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/openedx/edx-platform/lms/startup.py", line 11, in <module>
    settings.INSTALLED_APPS  # pylint: disable=pointless-statement
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/openedx/edx-platform/lms/envs/development.py", line 18, in <module>
    service_variant=SERVICE_VARIANT)
TypeError: get_logger_config() got an unexpected keyword argument 'debug'

**Comment by regisb** [comment]
I'm ready to bet your local edx-platform repository is on the master branch and not the ginkgo release branch?

**Comment by gmsk19** [comment]
Yes. You are absolutely right. Does that make a difference. I am going to switch to ginkgo.2 and rebuild and see what happens.

**Comment by gmsk19** [comment]
I am now using the ginkgo.master repository; Thanks for pointing it out regis. I now get the following error(on running the command python manage.py lms --settings=development print_setting STATIC_ROOT)

root@1f0e4b84d60d:/openedx/edx-platform# python manage.py lms --settings=development print_settings STATIC_ROOT
Traceback (most recent call last):
  File "manage.py", line 111, in <module>
    startup = importlib.import_module(edx_args.startup)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/openedx/edx-platform/lms/startup.py", line 12, in <module>
    settings.INSTALLED_APPS  # pylint: disable=pointless-statement
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named development

**Comment by gmsk19** [comment]
I have made some progress, definately a way forward.The build process goes onto compile sass files but hits a different issue. I tried to go the source of the issue, seems like some log file is missing. A similar issue reported(https://openedx.atlassian.net/browse/CRI-16)

**Stacktrace:**

python manage.py cms --settings=development print_settings STATIC_ROOT --format=value 2>/dev/null
NODE_ENV=production STATIC_ROOT_LMS=/openedx/data/staticfiles STATIC_ROOT_CMS=/openedx/data/staticfiles/d48ecf5 $(npm bin)/webpack
python manage.py lms --settings=development compile_sass lms 
python manage.py lms --settings=development collectstatic --noinput > /dev/null
---> pavelib.assets.watch_assets
find /openedx/edx-platform/lms /openedx/edx-platform/cms /openedx/edx-platform/common -type f -name "*.coffee"
python manage.py lms --settings=devstack print_settings STATIC_ROOT --format=value 2>/dev/null

**After running python manage.py lms --settings=devstack print_settings STATIC_ROOT** 

Build failed running pavelib.servers.lms: Subprocess return code: 1
root@7f267a45f5d8:/openedx/edx-platform# python manage.py lms --settings=devstack print_settings STATIC_ROOT 
Traceback (most recent call last):
  File "manage.py", line 112, in <module>
    startup.run()
  File "/openedx/edx-platform/lms/startup.py", line 52, in run
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 17, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/log.py", line 86, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python2.7/logging/config.py", line 794, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python2.7/logging/config.py", line 576, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'local': [Errno 2] No such file or directory
root@7f267a45f5d8:/openedx/edx-platform#

**Comment by regisb** [comment]
Apparently, the `paver lms --settings=development` triggers a `python manage.py lms --settings=devstack` (notice the different settings). This looks like a bug in edx-platform. So I would suggest *not* to run `paver lms`.

Instead, run:

    paver update_assets --settings=development lms

for collecting assets. And then run the LMS with:

    ./manage.py lms runserver 0.0.0.0:8000

I'll update the README later.

**Comment by gmsk19** [comment]
Regis,  
        Thank you for the update. The above suggested commands work. I am able to run the LMS on my local machine.

If I have to run the CMS, then i suppose I have to do the following, **please confirm**

make cms
paver update_assets --settings=development cms
./manage.py lms runserver 0.0.0.0:8001

p.: It has been a long thread. Thanks you for your patience.

**Comment by regisb** [comment]
It's **almost** correct :) the last instruction should be:

    ./manage.py cms runserver 0.0.0.0:8001

**Comment by gmsk19** [comment]
Finally i have both the LMS and CMS up and running on my local machine. Much Thanks to your guidance. _/\_ _/\_

**Comment by regisb** [comment]
Awesome! If you'd like, you can thank me by ordering peanut butter for me (from the Calve brand, not a different one): https://www.heimweewinkel.nl/products/calve-pindakaas

**Comment by gmsk19** [comment]
Sure Regis, Just need your delivery address. You can drop me a mail at gmsk19@gmail.com
