### ISSUE TITLE
[Windows] Getting ": invalid option" when running with local built images

### ISSUE THREAD

**Issue by tmrocha89** [regisb/openedx-docker#31]
Hello
1st Thank you for this project.
Issue: Can't run the openedx if the image that i'm using is built locally.

**Steps tp reproduce the error:**
**1.** Build openedx image with a custom tag
**2.** Change the tags in the docker-compose
**3.** Run `make all`

**Error Message**

> Configuration files were successfuly generated. You may now run the app containers.
> docker-compose run --rm -e USERID=666 -e SETTINGS=universal.production lms bash -c "wait-for-> > greenlight.sh && ./manage.py lms migrate"
> Starting edx.prod.mongodb       ... done
> Starting edx.prod.memcached     ... done
> Starting edx.prod.elasticsearch ... done
> Starting edx.prod.rabbitmq      ... done
> Starting edx.prod.mysql         ... done
> Starting edx.prod.forum         ... done
> : invalid option
> make: *** [migrate] Error 1

Maybe the problem is related with one of the following warning when building the image

> debconf: delaying package configuration, since apt-utils is not installed
> 
> 
> Get:146 http://archive.ubuntu.com/ubuntu xenial/universe amd64 npm all 3.5.2-0ubuntu4 [1586 kB]
> debconf: unable to initialize frontend: Dialog
> debconf: (TERM is not set, so the dialog frontend is not usable.)
> debconf: falling back to frontend: Readline
> debconf: unable to initialize frontend: Readline
> debconf: (This frontend requires a controlling tty.)
> debconf: falling back to frontend: Teletype
> dpkg-preconfigure: unable to re-open stdin:
> Fetched 32.0 MB in 24s (1331 kB/s)
> 
> 
> Cloning https://github.com/edx/codejail.git (to a320d43ce6b9c93b17636b2491f724d9e433be47) to /openedx/venv/src/codejail
> Could not find a tag or branch 'a320d43ce6b9c93b17636b2491f724d9e433be47', assuming commit.
> Requested codejail==0.0 from git+https://github.com/edx/codejail.git@a320d43ce6b9c93b17636b2491f724d9e433be47#egg=codejail==0.0 (from -r requirements/edx/github.txt (line 73)), but installing version None
> 
> 
> Step 12/25 : RUN pip install --src ../venv/src -r requirements/edx/base.txt
>  ---> Running in 71844a0d8b40
> DEPRECATION: --allow-external has been deprecated and will be removed in the future. Due to changes in the repository protocol, it no longer has any effect.
> DEPRECATION: --allow-unverified has been deprecated and will be removed in the future. Due to changes in the repository protocol, it no longer has any effect.
> 
> 
> Requested meliae==0.4.0 from https://files.pythonhosted.org/packages/98/c6/7fa12062ddfe1732d43b34b64a3fe99da958a88fa1d8b7550fe386a9ca01/meliae-0.4.0.tar.gz#sha256=976519ab02aaa6a8fb5f596dc4dd9f64fc9510b00e054979566e51c9be7cec99 (from -r requirements/edx/base.txt (line 75)), but installing version None

Any idea how to overcome this issue?
Thanks!

**Comment by regisb** [comment]
The `: invalid option` message makes me think there's a typo somewhere in your docker-compose file, probably in the lms or the cms sections. Could you post your docker-compose file here?

**Comment by tmrocha89** [comment]
No, I don-t believe that is some error on my docker-compose.
With docker I'm able to start all external services. So I did and tried to start lms from terminal (without using docker-compose) and I face the same problem.

But the time I tried to start lms from terminal I didn't try to mount the volumes.
And I'm doing this on a windows machine.

**Comment by regisb** [comment]
Indeed, I can't seem to find an error in the docker-compose file.
Maybe the error is related to volumes? I am not familiar with docker under windows. Can you try to comment out *all* the volume declarations in the docker-compose file and then run "make lms". If it doesn't work please paste the exact output here. If it does, try to uncomment the volume declarations one by one until it doesn't work anymore.

**Comment by tmrocha89** [comment]
I tested on ubuntu 16.04 machine and everything work as expected.
I'll check this weekend (_probably_), but this seems to be a problem with Windows.

**Comment by regisb** [comment]
Thanks! I'm sorry I can't help you more, but I don't have a Windows machine... Please report your findings!

**Comment by regisb** [comment]
@tmrocha89 did you make progress about windows support? If not, can I close this?

**Comment by regisb** [comment]
@tmrocha89 Unfortunately I don't have time to test this project under windows :-/ But thanks for the comment about USERID: I should take that into account if I decide that we should support windows.

**Comment by stackedsax** [comment]
We ran into this error.  It was related to Windows line-endings.  Remove all \r's and you'll be better.

**Comment by regisb** [comment]
@stackedsax thanks for your input!

1) In which file(s) did you remove the \r end of line characters?
2) Can you confirm that tutor works on windows?
3) How did you install `make`?

**Comment by kingram6865** [comment]
We had to clear the ms-dos carriage returns in app-entrypoint.sh.
After that, no more ":invalid option" errors.
