### ISSUE TITLE
ERROR: pull access denied for regis/openedx-xqueue

### ISSUE THREAD

**Issue by tony-h** [regisb/openedx-docker#33]
The Docker container doesn's appear to be public or it has been removed.
https://hub.docker.com/u/regis/

```
Pulling xqueue_consumer (regis/openedx-xqueue:ginkgo)...
ERROR: pull access denied for regis/openedx-xqueue, repository does not exist or may require 'docker login'
Makefile:22: recipe for target 'update' failed
make: *** [update] Error 1
```

**Comment by regisb** [comment]
Thanks for opening this issue! I'm aware of it: it is the Travis CI build that is in charge of pushing the image to docker hub, but it failed for some reason. For the moment, you may simply comment out the xqueue sections from the docker-compose.yml file.

**Comment by tony-h** [comment]
Awesome, thanks for the workaround. Thanks for putting this Open edX package together!

**Comment by regisb** [comment]
This should be fixed now \o/
