### ISSUE TITLE
standard_init_linux.go:178: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by saphemmy** [regisb/openedx-docker#38]
Pls help

Starting vklass_elasticsearch_1 ... 
Starting vklass_memcached_1 ... 
Starting vklass_mysql_1 ... h_1 ... done
Starting vklass_mysql_1 ... done
Starting vklass_rabbitmq_1 ... done
standard_init_linux.go:178: exec user process caused "exec format error"
Makefile:25: recipe for target 'provision' failed
make: *** [provision] Error 1

**Comment by regisb** [comment]
Hi! Can you please try to run the same command again? I would like to see the full command with the log.

**Comment by saphemmy** [comment]
okay i have done that several times...

**Comment by regisb** [comment]
Can you give the command that you are running with the complete log?

**Comment by saphemmy** [comment]
hold will try that before the end of the day...and pls can you give me the
command to get error logs.?

**Comment by regisb** [comment]
Just copy-paste the *complete* output from the console.

**Comment by saphemmy** [comment]
analyst@analyst-Dell-System-Inspiron-N4110:~/Desktop/virtualedubank$ make
all
./configure
Your website domain name for students (LMS). (default: "www.myopenedx.com"):
edubank.dev
Your website domain name for teachers (CMS). (default: "studio.myopenedx.com"):
studio.edubank.dev
Platform name/title (default: "My Open edX"): My Edubank

Configuration values were saved to  config/config.json
Generated config file config/openedx/lms.env.json (from template
config/openedx/templates/lms.env.json.templ)
Generated config file config/openedx/cms.env.json (from template
config/openedx/templates/cms.env.json.templ)
Generated config file config/openedx/lms.auth.json (from template
config/openedx/templates/lms.auth.json.templ)
Generated config file config/openedx/cms.auth.json (from template
config/openedx/templates/cms.auth.json.templ)
Generated config file config/openedx/provision.sh (from template
config/openedx/templates/provision.sh.templ)
Generated config file config/xqueue/universal.py (from template
config/xqueue/templates/universal.py.templ)
Generated config file config/mysql/auth.env (from template
config/mysql/templates/auth.env.templ)
Generated config file config/nginx/lms.conf (from template
config/nginx/templates/lms.conf.templ)
Generated config file config/nginx/cms.conf (from template
config/nginx/templates/cms.conf.templ)
Generated config file config/android/universal.yaml (from template
config/android/templates/universal.yaml.templ)

Configuration files were successfuly generated. You may now run the app
containers.
docker-compose pull
Pulling mongodb (mongo:3.0.14)...
3.0.14: Pulling from library/mongo
Digest:
sha256:0f245c03e7bbca6dc8dbb15be87614f19403496cf993f757a8ef170480a62393
Status: Image is up to date for mongo:3.0.14
Pulling smtp (namshi/smtp:latest)...
latest: Pulling from namshi/smtp
Digest:
sha256:0d1bd8288c2a3bfd14e9db4cd5abeae5b5887026ed99c05f634f9c45d5116360
Status: Image is up to date for namshi/smtp:latest
Pulling rabbitmq (rabbitmq:3.6.10)...
3.6.10: Pulling from library/rabbitmq
Digest:
sha256:7f8fe778a897bbfd66c76e464a3ba08d01769d00a856a1c638a5ddbcdf6468e0
Status: Image is up to date for rabbitmq:3.6.10
Pulling nginx (nginx:1.13)...
1.13: Pulling from library/nginx
Digest:
sha256:b1d09e9718890e6ebbbd2bc319ef1611559e30ce1b6f56b2e3b479d9da51dc35
Status: Image is up to date for nginx:1.13
Pulling elasticsearch (elasticsearch:1.5.2)...
1.5.2: Pulling from library/elasticsearch
Digest:
sha256:fa85d35947083a9b3f4e54299d86ccc2ff6567d21fa0b89fc4424f2a88c2fdaf
Status: Image is up to date for elasticsearch:1.5.2
Pulling forum (regis/openedx-forum:ginkgo)...
ginkgo: Pulling from regis/openedx-forum
Digest:
sha256:e838e3038bab5e397db47602ca5267afd815a9f0a54e247e7a3e9615373ff251
Status: Image is up to date for regis/openedx-forum:ginkgo
Pulling mysql (mysql:5.6.36)...
5.6.36: Pulling from library/mysql
Digest:
sha256:55cbc591a7ebc1c47458c97b8edbd2693c9e4ec5666f1ad8202a86a2e639e326
Status: Image is up to date for mysql:5.6.36
Pulling xqueue_consumer (regis/openedx-xqueue:ginkgo)...
ginkgo: Pulling from regis/openedx-xqueue
Digest:
sha256:80a4dae95326564726b154b43aafdf06f3a32c3d45190f581ec0efbe09ba649c
Status: Image is up to date for regis/openedx-xqueue:ginkgo
Pulling xqueue (regis/openedx-xqueue:ginkgo)...
ginkgo: Pulling from regis/openedx-xqueue
Digest:
sha256:80a4dae95326564726b154b43aafdf06f3a32c3d45190f581ec0efbe09ba649c
Status: Image is up to date for regis/openedx-xqueue:ginkgo
Pulling memcached (memcached:1.4.38)...
1.4.38: Pulling from library/memcached
Digest:
sha256:d83af2b8bd40c12e0bc91c969bed27c7a1631939c7bb73f95f11dfe00395d224
Status: Image is up to date for memcached:1.4.38
Pulling lms (regis/openedx:ginkgo)...
ginkgo: Pulling from regis/openedx
Digest:
sha256:aa5fe299e81d28102daca66700e644df693758b4b6467e3729c6266068e7628b
Status: Image is up to date for regis/openedx:ginkgo
Pulling lms_worker (regis/openedx:ginkgo)...
ginkgo: Pulling from regis/openedx
Digest:
sha256:aa5fe299e81d28102daca66700e644df693758b4b6467e3729c6266068e7628b
Status: Image is up to date for regis/openedx:ginkgo
Pulling cms (regis/openedx:ginkgo)...
ginkgo: Pulling from regis/openedx
Digest:
sha256:aa5fe299e81d28102daca66700e644df693758b4b6467e3729c6266068e7628b
Status: Image is up to date for regis/openedx:ginkgo
Pulling cms_worker (regis/openedx:ginkgo)...
ginkgo: Pulling from regis/openedx
Digest:
sha256:aa5fe299e81d28102daca66700e644df693758b4b6467e3729c6266068e7628b
Status: Image is up to date for regis/openedx:ginkgo
docker-compose run --rm lms bash -c "dockerize -wait tcp://mysql:3306
-timeout 20s && bash /openedx/config/provision.sh"
Creating virtualedubank_mongodb_1       ... done
Creating virtualedubank_smtp_1          ... done
Creating virtualedubank_rabbitmq_1      ... done
Creating virtualedubank_elasticsearch_1 ... done
Creating virtualedubank_memcached_1     ...
Creating virtualedubank_forum_1         ... done
Creating virtualedubank_memcached_1     ... done
Creating virtualedubank_forum_1         ...
standard_init_linux.go:178: exec user process caused "exec format error"
Makefile:25: recipe for target 'provision' failed
make: *** [provision] Error 1

**Comment by saphemmy** [comment]
analyst@analyst-Dell-System-Inspiron-N4110:~$ docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (i386)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent
it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://cloud.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/

**Comment by saphemmy** [comment]
could i connect you with teamviewer 12  please, really need this, could you pm saphemmy@gmail.com so i could share my id with you pls.

**Comment by regisb** [comment]
I can see that you are trying to run docker on a 32 bit machine:

     2. The Docker daemon pulled the "hello-world" image from the Docker Hub. (i386)

This is most certainly the problem. The Open edX images have been built for 64 bit systems. I'm no Docker expert, so I don't know how to build for i386 systems.

Please confirm that you are running a 32 bit OS by running:

    uname -a

The system hostname indicates that your computer is a Dell Inspiron N4110, right? The specs indicate that you should be able to install a 64 bit OS on this computer.

Unfortunately, maintaining this repo is not my full-time job, so I don't have time to do 1-1 video support.

**Comment by saphemmy** [comment]
will try it out on 64bit right away, thanks in advance will keep in-touch
