### ISSUE TITLE
make all error

### ISSUE THREAD

**Issue by aybase** [regisb/openedx-docker#40]
Hi, I cannot seem to get past make all...
----------------------------------------------
root@foobar:~/openedx-docker# make all
./configure
/usr/bin/env: ‘python’: No such file or directory
Makefile:19: recipe for target 'configure' failed
make: *** [configure] Error 127
----------------------------------------------
Running a fresh install of Ubuntu 16.04.4 x64 on Digital Ocean. Docker and Python 3 installed. Suggestions? much appreciated.

**Comment by tony-h** [comment]
It looks like the system doesn't know where the python executable is. Maybe something messed up during the init process?
Try running: `which python`

I don't know if these link will help, but you can check them out:
- https://stackoverflow.com/questions/3655306/ubuntu-usr-bin-env-python-no-such-file-or-directory
- https://stackoverflow.com/questions/11390206/usr-bin-env-python2-no-such-file-or-directory
- https://askubuntu.com/questions/942930/usr-bin-env-python-no-such-file-or-directory-

**Comment by tony-h** [comment]
Since you are running Python3, you can look at creating an alias:
https://askubuntu.com/questions/320996/how-to-make-python-program-command-execute-python-3#321000

**Comment by aybase** [comment]
Thanks for the links! I tried with Python v2.7.12 and made it through much of the process until I hit a migrate error:
_________________________________________________________________
...
  Applying third_party_auth.0008_auto_20170413_1455... OK
  Applying third_party_auth.0009_auto_20170415_1144... OK
  Applying third_party_auth.0010_add_skip_hinted_login_dialog_field... OK
  Applying third_party_auth.0011_auto_20170616_0112... OK
  Applying third_party_auth.0012_auto_20170626_1135...bash: line 1:    12 Killed                  ./manage.py lms migrate
Makefile:28: recipe for target 'migrate-openedx' failed
make: *** [migrate-openedx] Error 137
root@foobar:~/openedx-docker# 
_________________________________________________________________

**Comment by regisb** [comment]
@aybase this section of the readme should be of interest ;-) https://github.com/regisb/openedx-docker#running-migrations-killed

@tony-h thanks for the user support!

**Comment by aybase** [comment]
I've successfully installed openedx-docker. However I'm re-opening this issue to inform potential Digital Ocean users that their 4GB hosting tier will not suffice. I had to upgrade to 8GB to get the expected result.

@regisb gratitude for your excellent work.

**Comment by zacario-li** [comment]
> Hi, I cannot seem to get past make all...
> 
> ```
> ----------------------------------------------
> root@foobar:~/openedx-docker# make all
> ./configure
> /usr/bin/env: ‘python’: No such file or directory
> Makefile:19: recipe for target 'configure' failed
> make: *** [configure] Error 127
> ----------------------------------------------
> ```
> 
> Running a fresh install of Ubuntu 16.04.4 x64 on Digital Ocean. Docker and Python 3 installed. Suggestions? much appreciated.

run below cmd, have fun
```
update-alternatives --install /usr/bin/python python /usr/bin/python3 200
```
