### ISSUE TITLE
/usr/bin/env: ‘python’: No such file or directory

### ISSUE THREAD

**Issue by DerekCrosson** [regisb/openedx-docker#41]
Hello

When I run the following command:
sudo make all

I get this error:
./configure
/usr/bin/env: ‘python’: No such file or directory
Makefile:19: recipe for target 'configure' failed
make: *** [configure] Error 127

This is what I get when I run make info

uname -a
Linux ubuntu-s-2vcpu-4gb-lon1-01 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
-------------------------
docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
-------------------------
docker-compose --version
docker-compose version 1.18.0, build 8dd22a9
-------------------------
python --version
make: python: Command not found
Makefile:59: recipe for target 'info' failed
make: *** [info] Error 127

Any ideas?

**Comment by DerekCrosson** [comment]
Okay, solved :)

Used whereis python to find where python 2.7 and python 3 are.

Then updated the confugure file to point to the correct python path:

#! /usr/bin/python2.7

**Comment by regisb** [comment]
I just love it when users solve their own problems ;) However, it's a bit strange that you had python 2.7 and python3 installed, but did not have a `/usr/bin/python` file, and not even a `python` binary in your path...

Note: on most systems, you could have solved your problem without patching the `configure` file by manually creating a `python` executable:

    # run this as root
    ln -s /usr/bin/python2.7 /usr/local/bin/python
