### ISSUE TITLE
How do I install another language for openedx interface

### ISSUE THREAD

**Issue by emh2007** [regisb/openedx-docker#44]
Hello sir;
Can you please explain how can I install another language for open edx interface such as Arabic from Transifex

Thanks in advance

**Comment by regisb** [comment]
I have no idea. This is a generic Open edX question, not specific to this project. However, the Open edX documentation is lacking on this point. You probably simply need to set the django `LANGUAGE_CODE` setting: https://docs.djangoproject.com/en/2.0/ref/settings/#language-code
