### ISSUE TITLE
Correct placement of .json files?

### ISSUE THREAD

**Issue by natea** [regisb/openedx-docker#45]
i’m trying to load some settings from `lms.auth.json` and `cms.auth.json` and wondering how/where those files get read in openedx-docker

i’m using `production.py` and when i add the settings in that .py file, then they get loaded
but when i edit the files one level up in the “universal” folder, they appear to be getting ignored.
is this not the config dir that is read during runtime?

i notice these files (`lms.auth.json` and `cms.auth.json`) also exist in `/edxapp/config` and `/openedx/config`

where is the correct place to edit them in order that they’ll be read when the system starts up?

**Comment by regisb** [comment]
The correct location of the configuration files is `./config/openedx`. However, changes to those files will be overwritten every time you run `make configure` or make `all`. To make durable changes, you need to modify the file templates located in [`config/openedx/templates`](https://github.com/regisb/openedx-docker/tree/master/config/openedx/templates). 

The `edxapp/` folder should not exist, it was deleted in an older version of openedx-docker.

(As discussed on slack, the original issue had to do with incorrect setting naming)
