### ISSUE TITLE
How to deploy to kubernetes with Kompose?

### ISSUE THREAD

**Issue by wwj718** [regisb/openedx-docker#48]
hi @regisb,

I would like to use Kompose to deploy openedx-docker to k8s

Is this feasible?  Do you have any advice?

Thanks！

**Comment by regisb** [comment]
Hi @wwj718,
I have no idea, I never tried to deploy to Kubernetes. However, I would like to have your feedback on using kompose. What is the output of `kompose up`?

**Comment by wwj718** [comment]
@regisb  Thanks for you reply!

>  kompose takes a Docker Compose file and translates it into Kubernetes resources.

`kompose up` just like `docker-compose up`, but it will deploy docker images to kubernetes

Your [openedx-docker](https://github.com/regisb/openedx-docker) repo  is awesome! I want to  deploy it to k8s.  Make it easier for more people to use it (as SaaS)

**Comment by regisb** [comment]
Cool! Please comment here once you have tried kompose and list the issues you encountered. Maybe I'll add a section to the documentation to explain how to deploy to Kubernetes.

**Comment by wwj718** [comment]
hi, @regisb ,
I am sorry to tell you that the progress is not going well.
I was going to use [minikube](https://github.com/kubernetes/kompose/blob/master/docs/getting-started.md#minikube-and-kompose) to do experiments locally. But The network in China is extremely unstable.
This is my note for experimentation:[openedx-docker-k8s](https://blog.just4fun.site/openedx-docker-k8s.html)
My English is poor，so I write it  with Chinese . If you are interested，You can read it using google translation
If I make any progress, I will report it in time.

**Comment by regisb** [comment]
If I understand correctly, some issues may be related to the fact that the volumes are not properly declared in the custom open edx images. I'll try to find the time to take a look at this.

**Comment by wwj718** [comment]
Yes , you are right, the main problem is  volumes.
If you are willing to deal with it, it’s great!

**Comment by regisb** [comment]
Nope. Feel free to make a pull request.

**Comment by regisb** [comment]
Can you try again in a few minutes, once the images are updated on dockerhub? I made a change that (I hope) should fix the issue.

**Comment by wwj718** [comment]
@regisb Thanks a lot!
I will try again

**Comment by lohipoo** [comment]
Modify the docker-compose file, use volumes to storage configs, such as 
"volumes:
      - config_openedx:/openedx/config
...
volumes:
  config_openedx:
    driver: local"
then Kompose can translate these volumes into PersistentVolumeClaim,
However, I`m stuck in 'make cms' in this way.

**Comment by regisb** [comment]
I'm currently working on a native deployment of Open edX on Kubernetes... Stay tuned!

**Comment by lohipoo** [comment]
I`m so glad to hear that!thx!




null
