### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by mntw** [regisb/openedx-docker#50]
I've made a command `sudo make all` 
And get this:

```
docker run --rm -it --volume="/config:/openedx/config" \
	-e USERID=$(id -u) -e SILENT= -e ACTIVATE_HTTPS= -e ACTIVATE_XQUEUE= \
	regis/openedx-configurator

====================================
      Interactive configuration 
====================================
Your website domain name for students (LMS). (default: "www.myopenedx.com"): 
Your website domain name for teachers (CMS). (default: "studio.myopenedx.com"): 
Platform name/title (default: "My Open edX"): 

Configuration values were saved to  /openedx/config/config.json
Traceback (most recent call last):
  File "./configure.py", line 156, in <module>
    main()
  File "./configure.py", line 77, in main
    args.func(args)
  File "./configure.py", line 135, in substitute
    with codecs.open(args.src, encoding='utf-8') as fi:
  File "/usr/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: './config/openedx/templates/lms.env.json.templ'
Makefile:32: recipe for target 'configure' failed
make: *** [configure] Error 1

```

What the problem? And actually `./config/openedx/templates/lms.env.json.templ'` is exist and it's on it place.

**Comment by regisb** [comment]
The config folder is incorrectly mounted from `/config` : `--volume="/config:/openedx/config"`. Thus, the lms.env.json.templ file cannot be found from inside the container. This is because the PWD environment variable does not seem to be correctly defined in your environment.

What is the output of the following commands ?

```
echo $PWD
sudo echo $PWD
```

**Comment by mntw** [comment]
Ok. I ve found the solution. Instead to run `make all` with sudo i ve used the following command `sudo usermod -a -G docker $USER` and than docker will be able to `make all` without `sudo`. Everything works properly for now. Thank you very much, very handy preset.

**Comment by regisb** [comment]
For the record, please include the output of `make info`. It's strange that the content of the PWD environment variable is not correctly defined on your host.
