### ISSUE TITLE
 pull access denied for certbot_image, repository does not exist or may require 'docker login'.

### ISSUE THREAD

**Issue by cequn** [regisb/openedx-docker#52]
Unable to find image 'certbot_image:latest' locally
docker: Error response from daemon: pull access denied for certbot_image, repository does not exist or may require 'docker login'.
See 'docker run --help'.
Makefile:98: recipe for target 'https-certificate' failed
make: *** [https-certificate] Error 125

**Comment by regisb** [comment]
Hi @cequn,
What is the output of `make info`?

**Comment by regisb** [comment]
@cequn this was due to a typo in the Makefile. Please `git pull` and try again.
