### ISSUE TITLE
creating new user 'openedx' with UID 0 on make migrate

### ISSUE THREAD

**Issue by gmsk19** [regisb/openedx-docker#53]
I have been trying to deploy our stack on a Ubuntu machine on the cloud. When I try to issue a **make migrate** command i get the following error:

docker-compose run --rm -e USERID="$(id -u)" -p 8000:8000 lms bash -c "wait-for-greenlight.sh && ./manage.py lms migrate"
Starting openedxdocker_rabbitmq_1 ...
Starting openedxdocker_smtp_1 ... done
Starting openedxdocker_mongodb_1 ... done
Starting openedxdocker_memcached_1 ... done
creating new user 'openedx' with UID 0
useradd: UID 0 is not unique
Makefile:25: recipe for target 'migrate' failed
make: *** [migrate] Error 4

Any help would be much appreciated.

With Regards,
Shashi Kiran G M

**Comment by gmsk19** [comment]
I fiddled with the USERID, gave different values like 1000 . This error does get resolved but then while trying to migrate, it is unable to access the MYSQL and Mongo Databases.

**Comment by regisb** [comment]
It is really surprising that you are getting the `creating new user 'openedx' with UID 0` message. This message should *never* occur with UID 0, as indicated [in the entrypoint script](https://github.com/regisb/openedx-docker/blob/master/openedx/bin/docker-entrypoint.sh#L6).

1. Did you modify the entrypoint script?
2. To solve migration issues, make sure all containers are down before attempting to migrate, by running `make stop`.

**Comment by gmsk19** [comment]
Hi regis, 
          I was using an old version of the entrypoint script where the check in the entrypoint script was not with 0 but 1000. Will try this and revert with the status.

With regards,
Shashi Kiran G M

**Comment by regisb** [comment]
Ok I'll close this since it concerns an older release.
