### ISSUE TITLE
How to set up a production on AWS?

### ISSUE THREAD

**Issue by lukesodre** [regisb/openedx-docker#55]
I know this is not a issue, 

It's more like a manual, and Who knows we can publish the result of this thread at the README

I want to create a production on a AWS EC2 instance, 

The LMS worked fine, but the CMS I couldn't connect

I set up the IP address of EC2  my route at Route 53 to use my own domain

What do you guys think?
What are the recommendations?

**Comment by regisb** [comment]
Hi @lukesodre,
Maybe you can describe what kind of problem you are facing when trying to access the CMS? Did you configure the right host for the CMS? The address at which your CMS will be accessible can be found in `config/config.json` in the `CMS_HOST` entry.

**Comment by tony-h** [comment]
> How does it know where it should run the LMS or CMS, it has different ports? Who handles that?

While not explicitly listed in the instructions, the nginx configs list the various subdomain names used for Open edX.

You can get this information from:
```
nano ~/openedx-docker/config/nginx/cms.conf
nano ~/openedx-docker/config/nginx/lms.conf
```
`cms.conf`  shows: `   server_name studio.localhost studio.domain.com;`
`lms.conf`  shows: ` server_name localhost edx.domain.com preview.edx.domain.com;`

So, create your DNS records to match those subdomain names. You can then access the studio site. :)
I hope this helps!

**Comment by regisb** [comment]
Awesome! I'll close this issue for now, feel free to re-open if you have another ext2-related issue.
