### ISSUE TITLE
How to config cached

### ISSUE THREAD

**Issue by ctsdevteam** [regisb/openedx-docker#64]
Hi @regisb,

I getting a new problem with caching for mobile app. Whenever I change the course structure it reflected immediately on LMS but it doesn't on both android and ios app until I restart the "**openedx-docker_memcached_1**" docker and it reflected immediately on mobile app.

I also tried to edit the value on lms.env.json and cms.env.json like below but it doesnt effect at all
`"course_structure_cache": {
      "KEY_PREFIX": "course_structure",
      "TIMEOUT": "60",
      "BACKEND": "django.core.cache.backends.memcached.MemcachedCache",
      "KEY_FUNCTION": "util.memcache.safe_key",
      "LOCATION": "memcached:11211"
    }
      `

Please help me out with it and thank you in advance.

**Comment by regisb** [comment]
Did you fix the issue?

**Comment by ericjoyaether** [comment]
Thank you @regisb,

Yes, I found the way to do that already. I change the value on admin instead of changing the config file.

**Comment by ctsdevteam** [comment]
Thank you @regisb,

I managed it already. I changed the value on admin instead of changing the value on config file.

**Comment by shashikiranraifox** [comment]
> Thank you @regisb,
> 
> I managed it already. I changed the value on admin instead of changing the value on config file.

Hi CTS, which models need to be changed in Django Admin
