### ISSUE TITLE
Add SSL certificate on running instance 

### ISSUE THREAD

**Issue by shohrehahvar** [regisb/openedx-docker#65]
Hello,

Thanks for your codes.
We want to use the APIs that need authentication. I think for that we need https version of edx.
Please how we add SSL/TLS certificates for HTTPS access on running edx instance installed based on your 1 click installation ?

if we run ACTIVATE_HTTPS=1 make all, we get the following error:
docker run --rm -it --volume="$(pwd)/config/letsencrypt/:/openedx/letsencrypt/config/" --volume="$(pwd)/data/letsencrypt/:/etc/letsencrypt/" -p "80:80" --entrypoint "/openedx/letsencrypt/config/certonly.sh" certbot/certbot:latest

docker: Error response from daemon: driver failed programming external connectivity on endpoint hungry_austin (09e8477ce3cce23540a2360dddf85a7313f21280acbc222c82fc5372563f0fb0): Bind for 0.0.0.0:80 failed: port is already allocated.

Makefile:101: recipe for target 'https-certificate' failed

thanks,

regards,

**Comment by shohrehahvar** [comment]
Thanks for your reply ,  I got new error when I used make stop and then ACTIVATE_HTTPS=1 make all


  docker run --rm -it --volume="$(pwd)/config/letsencrypt/:/openedx/letsencrypt/config/" --volume="$(pwd)/data/letsencrypt/:/etc/letsencrypt/" -p "80:80" --entrypoint "/openedx/letsencrypt/config/certonly.sh" certbot/certbot:latest

docker: Error response from daemon: driver failed programming external connectivity on endpoint hungry_austin (09e8477ce3cce23540a2360dddf85a7313f21280acbc222c82fc5372563f0fb0): Bind for 0.0.0.0:80 failed: port is already allocated.

Makefile:101: recipe for target 'https-certificate' failed

Thanks, best regards,

**Comment by regisb** [comment]
That means that there is still a program running on port 80. Please run the following commands and paste here the complete output:

1. `docker ps`
2. `sudo netstat -nlptu | grep 80`

**Comment by shohrehahvar** [comment]
Thanks for your reply .  It is the output:
![image 2](https://user-images.githubusercontent.com/42036842/45413030-74666b00-b678-11e8-8b36-8f034c6c489f.png)

**Comment by shohrehahvar** [comment]
Thanks again. I run make all , then make stop and tried again  ACTIVATE_HTTPS=1 make all     , the result is this ;
docker run --rm -it --volume="$(pwd)/config/letsencrypt/:/openedx/letsencrypt/config/" --volume="$(pwd)/data/letsencrypt/:/etc/letsencrypt/" -p "80:80" --entrypoint "/openedx/letsencrypt/config/certonly.sh" certbot/certbot:latest

Saving debug log to /var/log/letsencrypt/letsencrypt.log

Plugins selected: Authenticator standalone, Installer None

An unexpected error occurred:

ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f09a72faad0>: Failed to establish a new connection: [Errno -3] Try again',))

Please see the logfiles in /var/log/letsencrypt for more details.

Makefile:101: recipe for target 'https-certificate' failed

**Comment by regisb** [comment]
It looks like the certbot container does not have access to the internet.
Can you tell me a bit more about the environment where you are trying to run your platform? Is it AWS, a local virtual machine, Digital Ocean?

**Comment by shohrehahvar** [comment]
my machin is ubuntu 16.4 
Thanks,

**Comment by regisb** [comment]
Is this your local computer? Did you see the [big warning](https://github.com/regisb/openedx-docker#ssltls-certificates-for-https-access-activate_https) about https not working for local development?

**Comment by shohrehahvar** [comment]
Ah yes I saw but I did not get that is related to be on local machine. Thanks a lot for your time. Sorry for that ;)
