### ISSUE TITLE
How do you configure openedx-docker such that the CMS & LMS can both be accessed on the web (i.e. not localhost)?

### ISSUE THREAD

**Issue by lot9s** [regisb/openedx-docker#68]
During the `make configure` installation step, I assigned the web address of the host machine to the CMS and a bogus web address to the LMS. I gave a bogus web address for the LMS because I assumed that a conflict would occur if both systems were bound to the same web address. Is this assumption incorrect?

Ideally, I would like to be able to navigate to both the CMS and LMS with a set of URLs that share the same base domain name (i.e. the host machine's web address). Can `openedx-docker` be configured to support this use case? If not, how might I implement this behavior?

Thanks!

**Comment by regisb** [comment]
Hi @lot9s!
I don't quite understand what you want to achieve. Can you give an example?

**Comment by lot9s** [comment]
Suppose that the host machine is at web address 999.999.999.999. Ideally, I would like to use the CMS and LMS by typing something like http://999.999.999.999/cms or http://999.999.999.999/lms into a web browser on a different machine.

Did that help clarify what I'm trying to achieve?

**Comment by regisb** [comment]
Ho ok I understand. In other words, you want to access the CMS and the LMS from different subpaths. This is AFAIK not possible with Open edX. At the very least it's strongly not recommended. The impossibility does not come from the installation method, but from limits in Open edX itself.

But do not despair! You need a domain name (e.g: myopenedx.org) that points to your server IP address (e.g: 999.999.999.999). It is perfectly possible to have multiple domain names, and also multiple subdomains of the main domain, that point to the same IP address. For instance: myopenedx.org, www.myopenedx.org and studio.myopenedx.org could all point to 999.999.999.999.

Once you have done that, just run `make all` again and give the complete subdomain + domain name for both the LMS and the CMS.

I let you close this issue once you confirm this proposed solution solves your problem.

**Comment by lot9s** [comment]
@regisb The proposed solution worked like a charm. 👍
