### ISSUE TITLE
How can I change  nginx port numbers?

### ISSUE THREAD

**Issue by frohro** [regisb/openedx-docker#69]
I am also running an instance of apache2 for other web duties on my server, and would like to have open edX use ports 8443, and 8080.  I went into the nginx running container and installed vi and edited the ports in /etc/nginx/... for the notes, cms and lms, but I can't find where to change port 443, and it still conflicts with apache2.  Do you have any tips?
I grepped your source code, and found a lot of :443's in there.  I am contemplating changing them and rebuilding, but before I try that, I thought asking might be better.

Thanks,
Rob

**Comment by tony-h** [comment]
The port numbers that are accessible from outside of the docker instances are defined in the [docker-compose.yml](https://github.com/regisb/openedx-docker/blob/master/docker-compose.yml) file. They come in pairs. The first number is the port to access the Docker instance from the outside (the published port). The second number is the internal port of the Docker instance. You would change your port configurations to 8080:80 and 8443:443, which forwards 8080 and 8443 to their respective ports in the docker instances. You can read about how Docker publishes ports at https://docs.docker.com/config/containers/container-networking/

For reference, here is my configuration. 
```
  nginx:
    image: nginx:1.13
    restart: unless-stopped
    ports:
      - "8091:80"
      - "4491:443"
```

**Comment by frohro** [comment]
Thanks, that worked perfectly, after I changed the previous edits.
Again, thanks!
Rob

**Comment by tony-h** [comment]
Glad to hear!

**Comment by regisb** [comment]
Thanks @tony-h for the support, as always ;)
@frohro unfortunately, there's no easy way to make these port numbers configurable, so you'll have to follow Tony-h's recommendation and edit them manually, for now.

**Comment by frohro** [comment]
One problem I'm having with this method is that edX creates URLs for emails, and maybe other places that do not contain the :8080.  I'm trying to figure out how to fix this.  Is it possible with VirtualHosts, or should I make configure with the :8080 on the domain name, or is there a better way to fix this?  Thanks for the help.  I'm just a teacher, not an IT professional.  :-)

**Comment by regisb** [comment]
@frohro you're right, the proposed solution isn't bulletproof. IMHO, it's really not practical to have to rely on http://domain:port urls. These urls are ugly and it's hard to give them to people, as most people just don't understand the `:port` part. 
Would you consider modifying your apache configuration on the host? All you would have to do is to setup a proxy from forwarding trafic from yourdomain:80 and yourdomain:443 to localhost:8080 and localhost:8443, respectively.

**Comment by frohro** [comment]
Thanks!  I'll give that a try, and report back here with the results in case someone else has similar needs.  I really appreciate your helpful suggestions!

**Comment by frohro** [comment]
Well, I'm trying, but so far without success.  I asked my admin to add edx.fweb.wallawalla.edu and studio.edx.fweb.wallawalla.edu to DNS and he did having them point to fweb.wallawalla.edu.  I added a site with this to try and forward the edx.fweb.wallawalla.edu traffic to fweb.wallawalla.edu:8080 and the studio.edx.fweb.wallawalla.edu to studio.fweb.wallawalla.edu.  Then I did a make configure and made the server name edx.fweb.wallawalla.edu for the lms, and studio.edx.fweb.wallawalla.edu for the cms, the URLs edx.fweb.wallawalla.edu and studio.edx.fweb.wallawalla.edu both end up pointing to fweb.wallawalla.edu:80.    Here is my apache2 site file.

<VirtualHost *:80>
        ServerName fweb.wallawalla.edu
        ServerAlias edx.fweb.wallawalla.edu
        ServerAdmin rob.frohne@wallawalla.edu
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        ProxyRequests Off
        <Proxy *>
          Order deny,allow
          Allow from all
        </Proxy>

        ProxyPass / http://edx.fweb.wallawalla.edu:8080/
        ProxyPassReverse / http://edx.fweb.wallawalla.edu:8080/

        <Location />
          Order allow,deny
          Allow from all
        </Location>

    </VirtualHost>
<VirtualHost *:80>
        ServerAlias studio.edx.fweb.wallawalla.edu
        ServerAdmin rob.frohne@wallawalla.edu
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        ProxyRequests Off
        <Proxy *>
          Order deny,allow
          Allow from all
        </Proxy>

        ProxyPass / http://studio.fweb.wallawalla.edu:8080/
        ProxyPassReverse / http://studio.fweb.wallawalla.edu:8080/

        <Location />
          Order allow,deny
          Allow from all
        </Location>

    </VirtualHost>

If I try fweb.wallawalla.edu:8080 or studio.fweb.wallawalla.edu:8080 I get a 400 error.  

If I make configure with fweb.wallawalla.edu and studio.fweb.wallawalla.edu, I can get there with these addresses :8080.  Does anyone have any suggestions?

And my apologies for elementary questions, I'm just a teacher trying to set open edx up for my class.  :-)

Thanks so much!
Rob

**Comment by tony-h** [comment]
I haven't used Apache as a proxy. So, just a suggestion. Have you trided:
`ProxyPass / localhost:8080/`

I wonder if `http://edx.fweb.wallawalla.edu:8080` is feeding the domain name back into Apache and it ends up in a loop.

I see that you define `ServerName fweb.wallawalla.edu` in the same config as your edx sub domain.
This could be another conflict because Apache treats `fweb.wallawalla.edu` and `edx.fweb.wallawalla.edu` as the same. When I visit edx.fweb.wallawalla.edu, it took me to the same web page as fweb.wallawalla.edu. You might have `ServerAlias edx.fweb.wallawalla.edu` defined another the fweb.wallawalla.edu.conf file.

Try separating the ServerNames and keeping them in their own config until you can narrow down the problem.

**Comment by regisb** [comment]
I agree with @tony-h: Apache needs to redirect to `localhost:8080`, which is the port that the nginx container listens on.

Let's assume that the expected urls for the LMS and the CMS are `edx.fweb.wallawalla.edu` and `studio.fweb.wallawalla.edu`, respectively, and let's recap the different steps you need to do, in the right order:


1. Modify the `ports` section from the nginx container in the [docker-compose.yml](https://github.com/regisb/openedx-docker/blob/master/docker-compose.yml#L43) file:

```
ports:
    - 8080:80
    - 8443:443
```

2. During `make configure` (or `make all`), type `edx.fweb.wallawalla.edu` as the website domain name for students and `studio.fweb.wallawalla.edu` as the website domain name for teachers.
3. Configure Apache to listen to `edx.fweb.wallawalla.edu` and `studio.fweb.wallawalla.edu` and redirect all traffic to `localhost:8080`. I'm not an Apache expert, but I believe this is the configuration you need:

```
< VirtualHost *:80 >
        ServerName edx.fweb.wallawalla.edu
        ProxyPreserveHost On
        ProxyRequests On
        ProxyPass / http://localhost:8080
        ProxyPassReverse / http://localhost:8080
< /VirtualHost >
< VirtualHost *:80 >
        ServerName studio.fweb.wallawalla.edu
        ProxyPreserveHost On
        ProxyRequests On
        ProxyPass / http://localhost:8080
        ProxyPassReverse / http://localhost:8080
< /VirtualHost >
```

Note that the `ProxyPreserveHost On` directives are important: they allow nginx to differentiate between traffic coming for the LMS or the CMS.

**Comment by regisb** [comment]
(tested, and it works)

**Comment by frohro** [comment]
Thanks!  That seems to have worked with one minor edit:

<VirtualHost *:80>
        ServerName edx.fweb.wallawalla.edu
        ProxyPreserveHost On
        ProxyRequests On
        ProxyPass / http://localhost:8080/
        ProxyPassReverse / http://localhost:8080/
</VirtualHost>
<VirtualHost *:80>
        ServerName studio.fweb.wallawalla.edu
        ProxyPreserveHost On
        ProxyRequests On
        ProxyPass / http://localhost:8080/
        ProxyPassReverse / http://localhost:8080/
</VirtualHost>

The edit is a / after the port number.  
Again, thanks!
Rob

**Comment by regisb** [comment]
cool! Please let me know how it goes running your platform.

**Comment by frohro** [comment]
Well, I'm having difficulty importing/exporting courses, with these port changes.  I went and deleted cookies from my site, because old efforts were unsuccessful.  I tried importing, and then exporting, and they just go forever on the second step of each process.  The name for the lms is edx.fweb.wallawalla, and that for the cms is studio.fweb.wallawalla.edu.  Here are some entries from the logs.  These messages just go spooling by "forever," or at least way longer that my patience would last.  :-)

cms_1            | 2018-10-02 02:33:22,075 INFO 125 [tracking] logger.py:50 - {"username": "frohro", "event_type": "/import_status/course-v1:wallawalla+engr354+fall2018/6004_1x.tar.gz", "ip": "172.18.0.1", "agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36", "host": "studio.edx.fweb.wallawalla.edu", "referer": "http://studio.edx.fweb.wallawalla.edu/import/course-v1:wallawalla+engr354+fall2018", "accept_language": "en-US,en;q=0.9", "event": "{\"POST\": {}, \"GET\": {}}", "event_source": "server", "context": {"user_id": 2, "org_id": "", "course_id": "", "path": "/import_status/course-v1:wallawalla+engr354+fall2018/6004_1x.tar.gz"}, "time": "2018-10-02T02:33:22.075483+00:00", "page": null}
cms_1            | 2018-10-02 02:33:24,039 INFO 125 [tracking] logger.py:50 - {"username": "frohro", "event_type": "/export_status/course-v1:wallawalla+test101+fall2018", "ip": "172.18.0.1", "agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36", "host": "studio.edx.fweb.wallawalla.edu", "referer": "http://studio.edx.fweb.wallawalla.edu/export/course-v1:wallawalla+test101+fall2018", "accept_language": "en-US,en;q=0.9", "event": "{\"POST\": {}, \"GET\": {}}", "event_source": "server", "context": {"user_id": 2, "org_id": "", "course_id": "", "path": "/export_status/course-v1:wallawalla+test101+fall2018"}, "time": "2018-10-02T02:33:24.038826+00:00", "page": null}
cms_1            | 2018-10-02 02:33:24,059 INFO 125 [tracking] logger.py:50 - {"username": "frohro", "event_type": "/import_status/course-v1:wallawalla+engr354+fall2018/6004_1x.tar.gz", "ip": "172.18.0.1", "agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36", "host": "studio.edx.fweb.wallawalla.edu", "referer": "http://studio.edx.fweb.wallawalla.edu/import/course-v1:wallawalla+engr354+fall2018", "accept_language": "en-US,en;q=0.9", "event": "{\"POST\": {}, \"GET\": {}}", "event_source": "server", "context": {"user_id": 2, "org_id": "", "course_id": "", "path": "/import_status/course-v1:wallawalla+engr354+fall2018/6004_1x.tar.gz"}, "time": "2018-10-02T02:33:24.059772+00:00", "page": null}
cms_1            | 2018-10-02 02:33:26,056 INFO 125 [tracking] logger.py:50 - {"username": "frohro", "event_type": "/export_status/course-v1:wallawalla+test101+fall2018", "ip": "172.18.0.1", "agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36", "host": "studio.edx.fweb.wallawalla.edu", "referer": "http://studio.edx.fweb.wallawalla.edu/export/course-v1:wallawalla+test101+fall2018", "accept_language": "en-US,en;q=0.9", "event": "{\"POST\": {}, \"GET\": {}}", "event_source": "server", "context": {"user_id": 2, "org_id": "", "course_id": "", "path": "/export_status/course-v1:wallawalla+test101+fall2018"}, "time": "2018-10-02T02:33:26.056487+00:00", "page": null}
cms_1            | 2018-10-02 02:33:26,076 INFO 125 [tracking] logger.py:50 - {"username": "frohro", "event_type": "/import_status/course-v1:wallawalla+engr354+fall2018/6004_1x.tar.gz", "ip": "172.18.0.1", "agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36", "host": "studio.edx.fweb.wallawalla.edu", "referer": "http://studio.edx.fweb.wallawalla.edu/import/course-v1:wallawalla+engr354+fall2018", "accept_language": "en-US,en;q=0.9", "event": "{\"POST\": {}, \"GET\": {}}", "event_source": "server", "context": {"user_id": 2, "org_id": "", "course_id": "", "path": "/import_status/course-v1:wallawalla+engr354+fall2018/6004_1x.tar.gz"}, "time": "2018-10-02T02:33:26.076040+00:00", "page": null}
cms_1            | 2018-10-02 02:33:28,056 INFO 125 [tracking] logger.py:50 - {"username": "frohro", "event_type": "/import_status/course-v1:wallawalla+engr354+fall2018/6004_1x.tar.gz", "ip": "172.18.0.1", "agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36", "host": "studio.edx.fweb.wallawalla.edu", "referer": "http://studio.edx.fweb.wallawalla.edu/import/course-v1:wallawalla+engr354+fall2018", "accept_language": "en-US,en;q=0.9", "event": "{\"POST\": {}, \"GET\": {}}", "event_source": "server", "context": {"user_id": 2, "org_id": "", "course_id": "", "path": "/import_status/course-v1:wallawalla+engr354+fall2018/6004_1x.tar.gz"}, "time": "2018-10-02T02:33:28.055750+00:00", "page": null}
cms_1            | 2018-10-02 02:33:28,078 INFO 125 [tracking] logger.py:50 - {"username": "frohro", "event_type": "/export_status/course-v1:wallawalla+test101+fall2018", "ip": "172.18.0.1", "agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36", "host": "studio.edx.fweb.wallawalla.edu", "referer": "http://studio.edx.fweb.wallawalla.edu/export/course-v1:wallawalla+test101+fall2018", "accept_language": "en-US,en;q=0.9", "event": "{\"POST\": {}, \"GET\": {}}", "event_source": "server", "context": {"user_id": 2, "org_id": "", "course_id": "", "path": "/export_status/course-v1:wallawalla+test101+fall2018"}, "time": "2018-10-02T02:33:28.077842+00:00", "page": null}
cms_1            | 2018-10-02 02:33:30,049 INFO 125 [tracking] logger.py:50 - {"username": "frohro", "event_type": "/export_status/course-v1:wallawalla+test101+fall2018", "ip": "172.18.0.1", "agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36", "host": "studio.edx.fweb.wallawalla.edu", "referer": "http://studio.edx.fweb.wallawalla.edu/export/course-v1:wallawalla+test101+fall2018", "accept_language": "en-US,en;q=0.9", "event": "{\"POST\": {}, \"GET\": {}}", "event_source": "server", "context": {"user_id": 2, "org_id": "", "course_id": "", "path": "/export_status/course-v1:wallawalla+test101+fall2018"}, "time": "2018-10-02T02:33:30.049523+00:00", "page": null}
cms_1            | 2018-10-02 02:33:30,075 INFO 125 [tracking] logger.py:50 - {"username": "frohro", "event_type": "/import_status/course-v1:wallawalla+engr354+fall2018/6004_1x.tar.gz", "ip": "172.18.0.1", "agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36", "host": "studio.edx.fweb.wallawalla.edu", "referer": "http://studio.edx.fweb.wallawalla.edu/import/course-v1:wallawalla+engr354+fall2018", "accept_language": "en-US,en;q=0.9", "event": "{\"POST\": {}, \"GET\": {}}", "event_source": "server", "context": {"user_id": 2, "org_id": "", "course_id": "", "path": "/import_status/course-v1:wallawalla+engr354+fall2018/6004_1x.tar.gz"}, "time": "2018-10-02T02:33:30.075142+00:00", "page": null}
cms_1            | 2018-10-02 02:33:32,063 INFO 125 [tracking] logger.py:50 - {"username": "frohro", "event_type": "/export_status/course-v1:wallawalla+test101+fall2018", "ip": "172.18.0.1", "agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36", "host": "studio.edx.fweb.wallawalla.edu", "referer": "http://studio.edx.fweb.wallawalla.edu/export/course-v1:wallawalla+test101+fall2018", "accept_language": "en-US,en;q=0.9", "event": "{\"POST\": {}, \"GET\": {}}", "event_source": "server", "context": {"user_id": 2, "org_id": "", "course_id": "", "path": "/export_status/course-v1:wallawalla+test101+fall2018"}, "time": "2018-10-02T02:33:32.063084+00:00", "page": null}
cms_1            | 2018-10-02 02:33:32,084 INFO 125 [tracking] logger.py:50 - {"username": "frohro", "event_type": "/import_status/course-v1:wallawalla+engr354+fall2018/6004_1x.tar.gz", "ip": "172.18.0.1", "agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36", "host": "studio.edx.fweb.wallawalla.edu", "referer": "http://studio.edx.fweb.wallawalla.edu/import/course-v1:wallawalla+engr354+fall2018", "accept_language": "en-US,en;q=0.9", "event": "{\"POST\": {}, \"GET\": {}}", "event_source": "server", "context": {"user_id": 2, "org_id": "", "course_id": "", "path": "/import_status/course-v1:wallawalla+engr354+fall2018/6004_1x.tar.gz"}, "time": "2018-10-02T02:33:32.083885+00:00", "page": null}
cms_1            | 2018-10-02 02:33:34,046 INFO 125 [tracking] logger.py:50 - {"username": "frohro", "event_type": "/export_status/course-v1:wallawalla+test101+fall2018", "ip": "172.18.0.1", "agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36", "host": "studio.edx.fweb.wallawalla.edu", "referer": "http://studio.edx.fweb.wallawalla.edu/export/course-v1:wallawalla+test101+fall2018", "accept_language": "en-US,en;q=0.9", "event": "{\"POST\": {}, \"GET\": {}}", "event_source": "server", "context": {"user_id": 2, "org_id": "", "course_id": "", "path": "/export_status/course-v1:wallawalla+test101+fall2018"}, "time": "2018-10-02T02:33:34.045866+00:00", "page": null}
cms_1            | 2018-10-02 02:33:34,068 INFO 125 [tracking] logger.py:50 - {"username": "frohro", "event_type": "/import_status/course-v1:wallawalla+engr354+fall2018/6004_1x.tar.gz", "ip": "172.18.0.1", "agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36", "host": "studio.edx.fweb.wallawalla.edu", "referer": "http://studio.edx.fweb.wallawalla.edu/import/course-v1:wallawalla+engr354+fall2018", "accept_language": "en-US,en;q=0.9", "event": "{\"POST\": {}, \"GET\": {}}", "event_source": "server", "context": {"user_id": 2, "org_id": "", "course_id": "", "path": "/import_status/course-v1:wallawalla+engr354+fall2018/6004_1x.tar.gz"}, "time": "2018-10-02T02:33:34.068198+00:00", "page": null}

I did have some success by turning off apache2 and changing the ports back to 80 and 443 in docker-compose.yml, but was unable to download the file produced by the export.  The import also failed, but I saw some messages that had edx.fweb.wallawalla.edu in them, leading me to believe I may need to start from scratch again.

I'll keep you posted on my progress.
Thanks for all the help you have guys have given me.
Rob

**Comment by regisb** [comment]
Let's move the conversation to #74

**Comment by regisb** [comment]
@frohro did you see 2f9766a3a193707be846520a535a70b070531610? It is no longer necessary for you to modify docker-compose.yml to edit the nginx ports.

**Comment by frohro** [comment]
Hi Regis,
I pulled the latest, created the .env file below, and did a make all, but it failed to start claiming that the ports were already in use.  I replaced the old docker-compose.yml and did a make all and it is back.  
Here is the appropriate portion of the docker-compose.yml that works:

  nginx:
    image: nginx:1.13
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
and here is the .env file:
OPENEDX_NGINX_PORT=8080
OPENEDX_NGINX_TLSPORT=8443

Thanks for your work on this!
Rob

**Comment by regisb** [comment]
I think you were mistaken by the commit message, which indicates incorrect variable names. You should write in `.env`:

```
NGINX_HTTP_PORT=8080
NGINX_HTTPS_PORT=8443
```

Please see the relevant documentation: https://github.com/regisb/openedx-docker/blob/master/README.md#cannot-start-service-nginx-driver-failed-programming-external-connectivity
