### ISSUE TITLE
Error on Android build: "cannot stat 'OpenEdXMobile/build/outputs/apk/*.apk': No such file or directory"

### ISSUE THREAD

**Issue by frohro** [regisb/openedx-docker#70]
`$ make android`

Errors occur because it couldn't stat directories under OpenEdXMobile including that one.  Creating them by hand with mkdir didn't seem to solve the issues.  Here are the last few lines of the build output.

```
BUILD SUCCESSFUL in 1m 57s
69 actionable tasks: 69 executed
cp: cannot stat 'OpenEdXMobile/build/outputs/apk/*.apk': No such file or directory
Makefile:145: recipe for target 'android' failed
make: *** [android] Error 1
```

Here is the make info:

```
frohro@fweb:~/openedx-docker$ make info
uname -a
Linux fweb 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
-------------------------
git rev-parse HEAD
fb36eb2d4eb19fc6865f890755823fc416be907d
-------------------------
docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:51 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:15 2018
  OS/Arch:          linux/amd64
  Experimental:     false
-------------------------
docker-compose --version
docker-compose version 1.21.2, build a133471
-------------------------
echo $EDX_PLATFORM_PATH

echo $EDX_PLATFORM_SETTINGS
```

**Comment by regisb** [comment]
Hi @frohro! Please run the following commands to further debug this issue.

```
make configure
make android-build
make android
```

Did this work? If not, what is the result of `ls -l data/android/`?

**Comment by frohro** [comment]
Thanks for the reply.  The results are the same.  Here are the last few lines of output from make android, and the ls:

BUILD SUCCESSFUL in 1m 59s
69 actionable tasks: 69 executed
cp: cannot stat 'OpenEdXMobile/build/outputs/apk/*.apk': No such file or directory
Makefile:145: recipe for target 'android' failed
make: *** [android] Error 1
frohro@fweb:~/openedx-docker$ ls -l data/android/
total 0

**Comment by regisb** [comment]
Can you give the complete output of the `make android` command?

**Comment by frohro** [comment]
I'm trying this on another machine with 16 GB instead of 8GB.  The make android-configure had no target.  the make android.  The results look similar, but with a different line of the Makefile blamed.

> Task :OpenEdXMobile:compileProdDebuggableJavaWithJavac 
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

D8: Stripped invalid locals information from 2 methods.
Warning: The rule `-keep public class *extends java.lang.annotation.Annotation {
  *;
}` uses extends but actually matches implements.

BUILD SUCCESSFUL in 2m 47s
69 actionable tasks: 69 executed
cp: cannot stat 'OpenEdXMobile/build/outputs/apk/*.apk': No such file or directory
Makefile:208: recipe for target 'android' failed
make: *** [android] Error 1
frohro@frohro-260:~/Projects/openedx-docker$ 

I don't have access to any machine with more that 16 GB.  There may be one somewhere here on campus though.  If you really think it is still RAM, let me know and I'll ask around.

Thanks for all your help!

Rob

**Comment by frohro** [comment]
Here is the line from make android-build.
/openedx-docker$ make android-build
make: *** No rule to make target 'android-build'.  Stop.

**Comment by regisb** [comment]
I renamed the make targets for android so that they are more compliant with the other commands. The new build command is `make build-android`.

This error is really strange. I'll investigate.

**Comment by regisb** [comment]
It was a simple issue of incorrect path... The path to the APK must have changed during the gradle upgrade. In a couple minutes (once [travis](https://travis-ci.org/regisb/openedx-docker/builds/436682250) finishes) you should be able to create your app with:

    make update
    make android
