### ISSUE TITLE
Mysql: "ERROR 1045 (28000): Access denied for user 'root'"

### ISSUE THREAD

**Issue by frohro** [regisb/openedx-docker#75]
Trying to install again from scratch with the docker-compose.yml modified for ports 8080 and 8443.  Here are the errors I got after a while.

Here is my history:
 587  docker system prune -a
  588  cd ..
  589  rm -rf openedx-docker
  590  sudo rm -rf openedx-docker
  591  git clone https://github.com/regisb/openedx-docker.git
  592  cd openedx-docker/
  593  vi docker-compose.yml 
  594  make all
  595  history

docker-compose -f docker-compose.yml -f docker-compose-notes.yml -f docker-compose-portainer.yml run --rm lms /openedx/config/provision.sh
Starting openedx-docker_mongodb_1   ... done
Starting openedx-docker_elasticsearch_1 ... done
Starting openedx-docker_smtp_1          ... done
Starting openedx-docker_rabbitmq_1      ... done
Starting openedx-docker_mysql_1         ... done
Starting openedx-docker_forum_1         ... done
2018/10/02 15:06:59 Waiting for: tcp://mysql:3306
2018/10/02 15:06:59 Connected to tcp://mysql:3306
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'172.19.0.9' (using password: YES)
Waiting for mysql database to be ready...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'172.19.0.9' (using password: YES)
Waiting for mysql database to be ready...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'172.19.0.9' (using password: YES)
Waiting for mysql database to be ready...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'172.19.0.9' (using password: YES)
Waiting for mysql database to be ready...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'172.19.0.9' (using password: YES)
Waiting for mysql database to be ready...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'172.19.0.9' (using password: YES)
Waiting for mysql database to be ready...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'172.19.0.9' (using password: YES)

I'll go try again.

**Comment by frohro** [comment]
Same error without the ports modified.

**Comment by regisb** [comment]
Don't worry about the ports, they shouldn't have an impact on anything, really.
Can you try running `make stop` and then `make databases` ?

**Comment by frohro** [comment]
Thanks!  I did a make stop, make databases, make assets, and make run, and it seems to be up again.
Thanks!
