### ISSUE TITLE
Enable Student Notes not available in Advanced Settings

### ISSUE THREAD

**Issue by frohro** [regisb/openedx-docker#79]
I did a make stop and git pull, and make all in which I enabled Student Notes, however, when did make run and went into studio advanced settings, to find the Enable Student Notes mentioned at the bottom of this page: https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/named-release-birch/exercises_tools/student_notes.html
I couldn't find it.  Any ideas?

Thanks,
Rob

**Comment by regisb** [comment]
@frohro : I didn't check that page when I added student notes, so I used an alternate way to activate notes for the course: I just added "notes" to the "Advanced Module List". However, you made me realise that notes can be more simply activated; for that, the ENABLE_EDXNOTES feature needs to be added to the configuration -- which I just did in commit 79a98e3.

**Comment by regisb** [comment]
(note that you will have to create an additional database and run migrations before notes work. So you will need to run `make stop && make databases`.)

**Comment by kikoShen** [comment]
> (note that you will have to create an additional database and run migrations before notes work. So you will need to run `make stop && make databases`.)

Is the additional database means a cloud database or create in local?

**Comment by regisb** [comment]
@kikoShen please don't comment on old closed issues :) Github issues are for solving bugs, not answering general questions. For asking questions, please head to http://discuss.overhang.io/
To answer your question: the notes database is a local mysql databases, stored in the same mysql container as the other databases.
