### ISSUE TITLE
rabbitmq container quit

### ISSUE THREAD

**Issue by frohro** [regisb/openedx-docker#80]
I'm not sure where to find out why this happened, but edx.fweb.wallawalla.edu was not allowing students to answer questions.  It would say “refresh the page or try again later” and the docker-compose logs -f gave me tons of these:

```
lms_worker_1     | 2018-10-05 03:13:57,617 ERROR 1 [celery.worker.consumer] consumer.py:366 - consumer: Cannot connect to amqp://guest:**@rabbitmq:5672//: [Errno -3] Temporary failure in name resolution.
lms_worker_1     | Trying again in 32.00 seconds...
```

and upon doing a docker stats, I found this:

```
CONTAINER ID        NAME                             CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
bc8a39997bad        openedx-docker_lms_worker_1      0.00%               223MiB / 7.672GiB     2.84%               108MB / 1.18kB      169MB / 328kB       5
7847837f835e        openedx-docker_cms_worker_1      0.00%               359.7MiB / 7.672GiB   4.58%               108MB / 1.11kB      68.9MB / 328kB      5
021210672a2c        openedx-docker_portainer_1       0.00%               6.438MiB / 7.672GiB   0.08%               108MB / 5.88kB      49MB / 8.32MB       12
09c3cc555761        openedx-docker_lms_1             0.01%               314.9MiB / 7.672GiB   4.01%               186MB / 52.8MB      225MB / 328kB       3
e4ab04e601f7        openedx-docker_cms_1             0.01%               252.7MiB / 7.672GiB   3.22%               108MB / 455kB       119MB / 328kB       3
c7edcc4ca7ab        openedx-docker_notes_1           0.00%               28.59MiB / 7.672GiB   0.36%               108MB / 0B          37.1MB / 0B         3
6f2eac8da630        openedx-docker_nginx_1           0.00%               3.641MiB / 7.672GiB   0.05%               152MB / 110MB       33.4MB / 0B         2
cc0f06e5e0c1        openedx-docker_forum_1           0.00%               178.2MiB / 7.672GiB   2.27%               110MB / 2.29MB      53.9MB / 8.19kB     12
f869428f4ac8        openedx-docker_mysql_1           0.04%               390.2MiB / 7.672GiB   4.97%               113MB / 7.78MB      114MB / 64.4MB      22
a11e6ebed8be        openedx-docker_memcached_1       0.00%               22.12MiB / 7.672GiB   0.28%               112MB / 39.5MB      8.45MB / 0B         7
c56426be8929        openedx-docker_mongodb_1         0.33%               28.84MiB / 7.672GiB   0.37%               110MB / 32.7MB      94.9MB / 208MB      27
b1bb4b095ca0        openedx-docker_smtp_1            0.00%               4.258MiB / 7.672GiB   0.05%               108MB / 4.33kB      46.9MB / 123kB      1
ebd2696b09ee        openedx-docker_elasticsearch_1   0.24%               415.5MiB / 7.672GiB   5.29%               108MB / 5.22kB      159MB / 213kB       69
^C
```

I would look at the docker logs, but I don't know what the container ID was.  Any hints other than recording the rabbitmq container ID for the next time?

Thanks,

Rob

**Comment by regisb** [comment]
Maybe we can capture the logs emitted by rabbitmq with `docker-compose logs -f rabbitmq`? Rabbitmq is supposed to restart in case of crash; I suspect that if it didn't restart, it's because it didn't start in the first place...

**Comment by frohro** [comment]
It has not occurred again.  I looked at the rabbitmq logs as you suggest, but it appears that when I restarted rabbitmq that the logs were dumped.  I'll keep an eye on this, and if it occurs again, I'll do better.  Sorry for the lack of data.

**Comment by regisb** [comment]
Ok, please post more info here if the incident happens again.

**Comment by frohro** [comment]
It just happened again.  I restarted the computer because updates required it, and thought that might fix my issue answering assignment questions: (We're sorry, there was an error with processing your request. Please try reloading your page and trying again.) But it the behavior persisted, so I did a docker-compose logs -f and found it couldn't contact rabbitmq like before, so I did a docker-compose logs -f rabbitmq and got this.  

Here is the tail of the rabbitmq log:

rabbitmq_1       | =INFO REPORT==== 29-Oct-2018::20:47:55 ===
rabbitmq_1       | closing AMQP connection <0.23606.3> (172.19.0.13:58186 -> 172.19.0.8:5672, vhost: '/', user: 'guest')
rabbitmq_1       | 
rabbitmq_1       | =INFO REPORT==== 29-Oct-2018::20:49:03 ===
rabbitmq_1       | accepting AMQP connection <0.23620.3> (172.19.0.13:58806 -> 172.19.0.8:5672)
rabbitmq_1       | 
rabbitmq_1       | =INFO REPORT==== 29-Oct-2018::20:49:03 ===
rabbitmq_1       | connection <0.23620.3> (172.19.0.13:58806 -> 172.19.0.8:5672): user 'guest' authenticated and granted access to vhost '/'
rabbitmq_1       | 
rabbitmq_1       | =INFO REPORT==== 29-Oct-2018::20:49:03 ===
rabbitmq_1       | closing AMQP connection <0.23620.3> (172.19.0.13:58806 -> 172.19.0.8:5672, vhost: '/', user: 'guest')
rabbitmq_1       | 
rabbitmq_1       | =INFO REPORT==== 29-Oct-2018::20:49:16 ===
rabbitmq_1       | accepting AMQP connection <0.23633.3> (172.19.0.13:59046 -> 172.19.0.8:5672)
rabbitmq_1       | 
rabbitmq_1       | =INFO REPORT==== 29-Oct-2018::20:49:16 ===
rabbitmq_1       | connection <0.23633.3> (172.19.0.13:59046 -> 172.19.0.8:5672): user 'guest' authenticated and granted access to vhost '/'
rabbitmq_1       | 
rabbitmq_1       | =INFO REPORT==== 29-Oct-2018::20:49:16 ===
rabbitmq_1       | closing AMQP connection <0.23633.3> (172.19.0.13:59046 -> 172.19.0.8:5672, vhost: '/', user: 'guest')
openedx-docker_rabbitmq_1 exited with code 255

I also get messages like this in the browser when trying to answer questions:
We're sorry, there was an error with processing your request. Please try reloading your page and trying again.
I'm going to restart rabbitmq, because I need this machine to run.  If you want me to do more next time, let me know what else you would like me to try.

Thanks!

Rob

**Comment by regisb** [comment]
@frohro,
Thanks for coming back with this new report. I just realised that rabbitmq had not restart policy, which explained why it was staying down. I still have to find out why it crashed in the first place, but this temporary fix should be sufficient for now.

**Comment by frohro** [comment]
Thanks for the fix!
