### ISSUE TITLE
Having trouble resetting tries or learner's state....

### ISSUE THREAD

**Issue by frohro** [regisb/openedx-docker#83]
So this may be operator error, or something else, but I can't seem to reset the number of tries or reset the learner's state.  I get messages like:
Error deleting student 'frohro's state on problem 'block-v1:wallawalla+engr354+2018+type@vertical+block@c11s1v2'. Make sure that the problem and student identifiers are complete and correct.
I got the problem number from the last part of the URL on studio.  

Any suggestions?

Thanks,
Rob

**Comment by frohro** [comment]
Upon closer inspection, the attempts were reset to zero, but the error message still remains when I do it.

**Comment by regisb** [comment]
Can you give the exact steps required to reproduce the issue? What kind of problem do I need to create? Does the reset happen in the lms or the cms?

**Comment by regisb** [comment]
I managed to reproduce the issue. AFAIU, the problem location is not the one from the url but the one that can be obtained by clicking the "Staff debug info" button on the problem page, in the LMS. For instance, for the "Problem 1: CMOS", the correct location of problem in course is not block-v1:Org+cs101+2018t4+type@vertical+block@c8s1v1 but block-v1:Org+cs101+2018t4+type@problem+block@cmos_cmos_SP14_Q1_P1A.

Was the behaviour different on edx.org?

**Comment by regisb** [comment]
I'll close this issue. Feel free to reopen if you don't agree with the proposed fix.

**Comment by frohro** [comment]
Thanks Regis!   I appreciate you taking the time to help me learn this platform.  It is working well for me.  I really appreciate all your work!
