### ISSUE TITLE
Comprehensive theming

### ISSUE THREAD

**Issue by frob** [regisb/openedx-docker#88]
In the [comprehensive theming guide](https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/ecommerce/theming.html) it says to set to enable comprehensive theming to set some settings in the lms.env.json file. In general I have noticed that not all of the configuration is here. What am I missing? Do I add the config to that file in /config?

**Comment by regisb** [comment]
Are you referring to the theming of edx-platform or ecommerce? Your link points to the ecommerce documentation, but I'll assume you actually want to theme edx-platform. Here's the relevant documentation: https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/changing_appearance/theming/enable_themes.html

Basically, edx-platform configuration can be found in three places:
1. The python files in lms/envs and cms/envs
2. The "env files" lms.env.json and cms.env.json
3. The "auth files"  lms.auth.json and cms.auth.json

The env and auth files are useless by themselves, as they need to be parsed in the python files.  Without proper parsing, their values are not taken into account. In openedx-docker, we slimmed down the env/auth files by relying on the default values defined in the python files. If we are fine with the default value for a specific setting, we don't bother to specify it in the env/auth files. 

For theming, the documentation suggests adding the ENABLE_COMPREHENSIVE_THEMING and COMPREHENSIVE_THEME_DIRS variables to the env files. You can just as well modify them from the production.py/development.py configuration files. I suggest you modify the templates, inside configurator/templates.

Theming should be supported out of the box for openedx-docker, so I'll leave this issue open and try to come up with an adequate solution.

**Comment by frob** [comment]
I got it working, this is how I did it. 

1. Post configuration I added the ENABLE_COMPREHENSIVE_THEMING and COMPREHENSIVE_THEME_DIRS to the env files in config. 
1. I added new volumes to the site mapping src/themes to /openedx/edx-platform/themes/custom. This needed to be added to the lms, cms, lms_worker, and cms_worker.
1. I put my theme into my src/themes directory as per the documentation.

**Comment by kbitr** [comment]
@regisb Did you change the procedure described in the [docs](http://docs.tutor.overhang.io/en/latest/customise.html#custom-themes)? The `make build-openedx` command is not available anymore.

Plus, any advice on how to add the main site as a "Site" in the Django configuration interface? I added the main site under `http://<domain>/admin/sites/site/` and added the theme under `http://localhost/admin/theming/sitetheme/`. Should this work?

**Comment by regisb** [comment]
@kbitr Did you run the `build-openedx` command from inside the `build` folder? On upgrading from openedx-docker to tutor, I decided to split the repo in several subfolders. All build-related commands should now be run inside the `build` folder.

> Plus, any advice on how to add the main site as a "Site" in the Django configuration interface? I added the main site under http://<domain>/admin/sites/site/ and added the theme under http://localhost/admin/theming/sitetheme/. Should this work?

Yes, it should :) But you should be careful to create a site with the right domain name. For instance, if you access your site at http://www.myopenedx.com, then the site domain should be www.myopenedx.com. If you access the site at http://localhost:8000 then you should create a "localhost:8000" site.

> Are there any themes provided by default? I remember that the console named the compilation of different themes in other versions at deployment.

The only provided theme is open-edx, which is the default theme. This makes the docker images much lighter. You can for instance add the edx.org theme by copying the edx-platform/themes/edx.org folder to build/openedx/themes.

**Comment by kbitr** [comment]
@regis Paying attention the the right Makefiles did the trick for compilation, thanks. However, I am too stupid. I added four themes which I assume to work with Hawthorn. And did this: 

> Plus, any advice on how to add the main site as a "Site" in the Django configuration interface? I added the main site under http://localhost/admin/sites/site/ and added the theme under http://localhost/admin/theming/sitetheme/. Should this work?

For the site deployed in my local docker container, configured as "localhost" at `make all` and added "localhost" to themes, doesn't show any change. Using a fresh browser, no cache. Or am I missing something? The changes should be obviously visible, right?

**Comment by regisb** [comment]
Please try the following:

```
cd build
make build-openedx # you should see notifications about your themes being compiled

cd ../deploy/local
make stop
make assets
make run # then access your site at http://localhost
```

If it does not work, please post here the following informations:

1. The output of `docker-compose logs --tail=100 lms` (inside the `deploy/local` folder)
2. The output of `ls ./data/openedx/staticfiles` (inside the tutor root folder)
3. The two screenshots from the django admin for your site and theme

**Comment by kbitr** [comment]
Okay, that worked, thanks! Apparently I wasn't aware that the containers had to be stopped, then asset and then run again. Can you shortly mention why?

**Comment by regisb** [comment]
Well, we need to run the `assets` command in order to copy the assets to the nginx webserver: in production, static assets are served by nginx, and not by the lms/cms. Does that make sense?

Then, there is the questions of restarting the containers. It's not very clear to me why, but it seems to me that when you don't stop the containers, the old containers keep running. For instance:

```
make daemon
make build-openedx
make restart-openedx
```

Then, I honestly do not know whether the newly-built containers will be running, or just the older version. If you find some documentation on this, then I'm interested.
