### ISSUE TITLE
make https-certificate when hosts are forwarded....

### ISSUE THREAD

**Issue by frohro** [regisb/openedx-docker#90]
This issue is coming because I have apache2 running on the server, and so I forwarded ports 8080 to nginx on the openedx running on docker with your kind help as described on issue #69.  I would like to switch over to using https from http which I did originally because I wanted to take the path of least trouble to get things going initially.  I'm now happy with the way things are going and decided to try and make things a little more secure so I started to get https going like this, but got an error because port 80 is in use by apache2.  Is there a place I can configure https to use port 8080 like you showed me how to do in issue $69?
Here is the result from my attempt:

 ```
frohro@fweb:~/openedx-docker$ make https-certificate
docker run --rm -it --volume="/home/frohro/openedx-docker/config/letsencrypt/:/openedx/letsencrypt/config/" --volume="/home/frohro/openedx-docker/data/letsencrypt/:/etc/letsencrypt/" -p "80:80" --entrypoint "/openedx/letsencrypt/config/certonly.sh" certbot/certbot:latest
Unable to find image 'certbot/certbot:latest' locally
latest: Pulling from certbot/certbot
c67f3896b22c: Pull complete 
dfa69c832a12: Pull complete 
0581302b23ff: Pull complete 
0f88dc6218e6: Pull complete 
57baa4381dc2: Pull complete 
30b8d9ad61c8: Pull complete 
1df82cea0901: Pull complete 
bd9114e79a85: Pull complete 
91b543425724: Pull complete 
aeec41c06999: Pull complete 
Digest: sha256:3c82c0b8f2902248cf29dda038e26087ede1a7e491ccae1ff47901b2232b1fae
Status: Downloaded newer image for certbot/certbot:latest
docker: Error response from daemon: driver failed programming external connectivity on endpoint nifty_goldwasser (1ee92fb61ae9c211214c113571821aa766cd347e49eae871d2f777effd2c26b3): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use.
Makefile:200: recipe for target 'https-certificate' failed
make: *** [https-certificate] Error 125
```

Thanks!

Rob

**Comment by regisb** [comment]
You need to stop the Apache server in order to generate the SSL certificate:

    sudo systemctl stop apache2

Then create the certificates:

    make https-certificate

Check that the certificates were successfully downloaded in `/path/to/openedx-docker/data/letsencrypt/live/fweb.wallawalla.edu`. You will probably have to change the permissions of those files so that Apache can read them. Something similar to:

    chgrp -R www-data /path/to/openedx-docker/data/letsencrypt/live/
    chmod -R g+r /path/to/openedx-docker/data/letsencrypt/live/

Note that you should have only one certificate both for the studio and the lms.

Then, configure Apache2 to accept connections on port 443 and with SSL support:

```
<VirtualHost *:443>
    ...
    SSLEngine on
    SSLCertificateFile    /path/to/openedx-docker/data/letsencrypt/live/fweb.wallawalla.edu/fullchain.pem
    SSLCertificateKeyFile   /path/to/openedx-docker/data/letsencrypt/live/fweb.wallawalla.edu/privkey.pem
```

Restart Apache : 

    sudo systemctl restart apache2

And that *should work.

**Comment by frohro** [comment]
Thanks Régis!  This worked.  I put in a redirect for the port 80 to https:// and that made it transparent to my students I hope as well.
