### ISSUE TITLE
Proxy breaks View Live in Studio

### ISSUE THREAD

**Issue by frob** [regisb/openedx-docker#93]
I have changed the setting in `config/openedx/cms.env.json` and `config/openedx/lms.env.json` but I cannot get the urls to be correct in those links. When I change `LMS_BASE` in these configruation files my proxy sends me back a `Bad Request (400) page`

If I don't change these then everything works (as far as I can tell), but the "View Live" button in studio shows the url to the local proxy.

**Comment by frob** [comment]
Some more info. I have changed my proxy to use localhost:port instead of a local url and now the View Live link can be set in the cms.env.json file. But I still have a related issue in the LMS.

The links in the LMS that go to course blocks are all localhost:port. As far as I can tell these are the only urls that are now wrong. Am I missing a url in the config that I need to set?

**Comment by regisb** [comment]
In order to change the url used by the "View Live" button, you should not modify the `LMS_BASE` setting, but the `PREVIEW_LMS_BASE` setting, which can be found in lms.env.json and cms.env.json.

Usually, "Bad Request (400)" errors happen when the Django `ALLOWED_HOSTS` setting does not contain the proper value. See the [django documentation](https://docs.djangoproject.com/en/2.1/ref/settings/#allowed-hosts) for explanations.

Note that you *cannot* have `PREVIEW_LMS_BASE == LMS_BASE`, otherwise you will get 404 errorson course pages (see #11).

**Comment by regisb** [comment]
What is the value of `PREVIEW_LMS_BASE` in `config/openedx/lms.env.json`?

**Comment by frob** [comment]
I had to obfuscate it a little bit because it is a client project.

`preview-project.dev.example.com`

The preview buttons work now, but the issue is the "Start Course" and unit block links.

**Comment by regisb** [comment]
Some more questions to clarify:

1. What is the url of the page where you observe the problem?
2. What is the configuration of the proxy?

**Comment by regisb** [comment]
Can you try to modify the proxy config to include the following?

```
  location / {
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header Host $http_host;
    proxy_pass  http://localhost:3080;
}
```

then `sudo service nginx reload`.

[Django uses the Host header](https://docs.djangoproject.com/en/1.11/ref/request-response/#methods) to compute the absolute url and I believe Open edX uses the X-Forwarded-* headers.

**Comment by frob** [comment]
If I set any of those it gives me the `Bad Request (400)`

**Comment by regisb** [comment]
Nonetheless, can you give the value of `ALLOWED_HOSTS` so that I can better understand the issue? Since I do not know which values were given during configuration, I do not know the content of this variable.

**Comment by frob** [comment]
Here is the value of `ALLOWED_HOSTS` the lms `production.py` file.

```
ALLOWED_HOSTS = [
    ENV_TOKENS.get('LMS_BASE'),
    FEATURES['PREVIEW_LMS_BASE'],
    '127.0.0.1', 'localhost', 'preview.localhost',
    '127.0.0.1:8000', 'localhost:8000', 'preview.localhost:8000',
]
```

**Comment by regisb** [comment]
So LMS_BASE must be equal to `edx-project.dev.example.com`. I'm not sure I correctly understood your previous explanations; what is the current value of LMS_BASE in config/openedx/lms.env.json ?

**Comment by frob** [comment]
Okay, yeah, that is the problem. nginx was forwarding on the proxy through a local url: `edx-project.local.example.net` and I was connecting through `edx-project.dev.example.net` so setting the `proxy_set_header Host $http_host` was passing an unacceptable value to django. Thus, giving me error 400 from django. It worked when passing to `localhost` because `localhost` is in the list of ALLOWED_HOSTS.

I probably need to add `proxy_set_header Host $http_host` back to the nginx proxy pass configuration and add `edx-project.dev.example.net` to that ALLOWED_HOST array. I will try that and get back to you. Thank you for all your help on this.

**Comment by regisb** [comment]
Awesome! I'll close this then.

**Comment by frob** [comment]
hmmm, not exactly closed yet. I did all that and got the same result. Checking the lms log I am not sure it is even getting there. Nginx logs is just showing " - " for the host. I thought the response was coming from Django but I am not sure as nothing is going into the log.

**Comment by regisb** [comment]
I managed to setup an nginx proxy that points to the dockerized nginx. This is what I did:

```
➭ cat openedx-docker/.env 
NGINX_HTTP_PORT=180
NGINX_HTTPS_PORT=1443
```
```
➭ cat /etc/nginx/sites-enabled/mydomain
server {
    listen          80;
    server_name   mydomain.com;
    location / {
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $http_host;
        proxy_pass  http://localhost:180;
    }
}
```

Note that I did *not* tweak the configuration files from openedx-docker/config. I just run `make configure` and set mydomain.com as the domain name for students.

When I go to http://mydomain.com/courses/course-v1:org+video1+01/course/ I see that links from the course summary point (correctly) to mydomain.com urls, e.g: http://mydomain.com/courses/course-v1:org+video1+01/jump_to/block-v1:org+video1+01+type@vertical+block@b9b85674087f4bbf9759da4d75f8dbd1
Links were incorrectly pointing to http://localhost:180/ when the `proxy_set_header` directives were missing.

I suggest you compare your configuration to mine and fix the differences.

**Comment by frob** [comment]
hmmm, same result. 

Did you set mydomain.com in your host file do direct everything to 127.0.0.1 or did you use a remote server. I don't know why it would matter, I am just looking for differences.

I think I have enough info to debug, and a hacky solution in place to keep my authors happy for the time being. Thank you very much for all your help, I will report back if/when I get this working.

**Comment by frob** [comment]
here is a bit more info:

from the proxy nginx logs:

```
2018/11/16 14:59:00 [error] 17182#0: *16083 connect() failed (111: Connection refused) while connecting to upstream, client: 50.198.167.161, server: edx-project.dev.example.net, request: "GET / HTTP/1.1", upstream: "http://[::1]:3080/", host: "edx-project.dev.example.net"
```

It only breaks if I set the `Host` in the proxy header. Nothing else causes the error.
