### ISSUE TITLE
Student notes error's.

### ISSUE THREAD

**Issue by roblhibbard** [regisb/openedx-docker#96]
When I try and load notes this is the error received.

## Unexpected behavior

<pre>lms_1_ef3f9eba1413 | 2018-11-17 05:39:13,348 INFO 11 [tracking] logger.py:50 - {"username": usert", "event_type": "/courses/course-v1:CHS+FP101+2018_S1/edxnotes/", "ip": "184.155.240.3", "agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36", "host": "hibbardsclass.org", "referer": "http://hibbardsclass.org/login?next=/courses/course-v1%3ACHS%2BFP101%2B2018_S1/edxnotes/", "accept_language": "en-US,en;q=0.9", "event": "{\"POST\": {}, \"GET\": {}}", "event_source": "server", "context": {"course_user_tags": {}, "user_id": 3, "org_id": "CHS", "course_id": "course-v1:CHS+FP101+2018_S1", "path": "/courses/course-v1:CHS+FP101+2018_S1/edxnotes/"}, "time": "2018-11-17T05:39:13.348252+00:00", "page": null}
nginx_1_5de25b445004 | 2018/11/17 05:39:13 [error] 8#8: *8 notes could not be resolved (3: Host not found), client: 184.155.240.3, server: notes.localhost, request: "GET /api/v1/annotations/?course_id=course-v1%3ACHS%2BFP101%2B2018_S1&user=9e026ca0bbc72a6bcdfa731f42d1f7cd&page_size=25&page=1 HTTP/1.1", host: "notes.hibbardsclass.org"
nginx_1_5de25b445004 | 184.155.240.3 - - [17/Nov/2018:05:39:13 +0000] "GET /api/v1/annotations/?course_id=course-v1%3ACHS%2BFP101%2B2018_S1&user=9e026ca0bbc72a6bcdfa731f42d1f7cd&page_size=25&page=1 HTTP/1.1" 502 166 "-" "python-requests/2.9.1" "-"
lms_1_ef3f9eba1413 | 2018-11-17 05:39:13,560 ERROR 11 [edxnotes.helpers] helpers.py:350 - Invalid JSON response received from notes api: response_content=<html>
lms_1_ef3f9eba1413 | <head><title>502 Bad Gateway</title></head>
lms_1_ef3f9eba1413 | <body bgcolor="white">
lms_1_ef3f9eba1413 | <center><h1>502 Bad Gateway</h1></center>
lms_1_ef3f9eba1413 | <hr><center>nginx</center>
lms_1_ef3f9eba1413 | </body>
lms_1_ef3f9eba1413 | </html>
lms_1_ef3f9eba1413 |
lms_1_ef3f9eba1413 | 2018-11-17 05:39:13,561 ERROR 11 [root] signals.py:17 - Uncaught exception from None
lms_1_ef3f9eba1413 | Traceback (most recent call last):
lms_1_ef3f9eba1413 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
lms_1_ef3f9eba1413 |     response = get_response(request)
lms_1_ef3f9eba1413 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
lms_1_ef3f9eba1413 |     response = self._get_response(request)
lms_1_ef3f9eba1413 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
lms_1_ef3f9eba1413 |     response = self.process_exception_by_middleware(e, request)
lms_1_ef3f9eba1413 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
lms_1_ef3f9eba1413 |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
lms_1_ef3f9eba1413 |   File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 185, in inner
lms_1_ef3f9eba1413 |     return func(*args, **kwargs)
lms_1_ef3f9eba1413 |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
lms_1_ef3f9eba1413 |     return view_func(request, *args, **kwargs)
lms_1_ef3f9eba1413 |   File "/openedx/edx-platform/lms/djangoapps/edxnotes/views.py", line 62, in edxnotes
lms_1_ef3f9eba1413 |     notes_info = get_notes(request, course)
lms_1_ef3f9eba1413 |   File "/openedx/edx-platform/lms/djangoapps/edxnotes/helpers.py", line 351, in get_notes
lms_1_ef3f9eba1413 |     raise EdxNotesParseError(_("Invalid JSON response received from notes api."))
lms_1_ef3f9eba1413 | EdxNotesParseError: Invalid JSON response received from notes api.
lms_1_ef3f9eba1413 | 2018-11-17 05:39:13,562 ERROR 11 [django.request] exception.py:135 - Internal Server Error: /courses/course-v1:CHS+FP101+2018_S1/edxnotes/
lms_1_ef3f9eba1413 | Traceback (most recent call last):
lms_1_ef3f9eba1413 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
lms_1_ef3f9eba1413 |     response = get_response(request)
lms_1_ef3f9eba1413 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
lms_1_ef3f9eba1413 |     response = self._get_response(request)
lms_1_ef3f9eba1413 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
lms_1_ef3f9eba1413 |     response = self.process_exception_by_middleware(e, request)
lms_1_ef3f9eba1413 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
lms_1_ef3f9eba1413 |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
lms_1_ef3f9eba1413 |   File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 185, in inner
lms_1_ef3f9eba1413 |     return func(*args, **kwargs)
lms_1_ef3f9eba1413 |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
lms_1_ef3f9eba1413 |     return view_func(request, *args, **kwargs)
lms_1_ef3f9eba1413 |   File "/openedx/edx-platform/lms/djangoapps/edxnotes/views.py", line 62, in edxnotes
lms_1_ef3f9eba1413 |     notes_info = get_notes(request, course)
lms_1_ef3f9eba1413 |   File "/openedx/edx-platform/lms/djangoapps/edxnotes/helpers.py", line 351, in get_notes
lms_1_ef3f9eba1413 |     raise EdxNotesParseError(_("Invalid JSON response received from notes api."))
lms_1_ef3f9eba1413 | EdxNotesParseError: Invalid JSON response received from notes api.
nginx_1_5de25b445004 | 184.155.240.3 - - [17/Nov/2018:05:39:13 +0000] "GET /courses/course-v1:CHS+FP101+2018_S1/edxnotes/ HTTP/1.1" 500 9855 "http://hibbardsclass.org/login?next=/courses/course-v1%3ACHS%2BFP101%2B2018_S1/edxnotes/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36" "-"</pre>

Here is the LMS Oauth2 - client 

2   notes
Name:  edx-notes
Url:    Currently: http://notes.hibbardsclass.org
Change: 
http://notes.hibbardsclass.org

Your application's URL.
Redirect uri:
Currently: http://notes.hibbardsclass.org/complete/edx-oidc/
Change: 
http://notes.hibbardsclass.org/complete/edx-oidc/

Your application's callback URL
Client id:
notes
Client secret: K1zOw1ezeaX0MVwnRH5uqCoX
Client type:
Logout uri:  Currently: http://notes.hibbardsclass.org/logout/
Change:  http://notes.hibbardsclass.org/logout/

Your application's logout URL
   http://notes.hibbardsclass.org/logout/

Here is the lms.env.json file.

"SITE_NAME": "hibbardsclass.org",
  "BOOK_URL": "",
  "LOG_DIR": "/openedx/data/logs",
  "LOGGING_ENV": "sandbox",
  "OAUTH_OIDC_ISSUER": "http://hibbardsclass.org/oauth2",
  "PLATFORM_NAME": "Hibbards Open edX",
  "FEATURES": {
    "PREVIEW_LMS_BASE": "preview.hibbardsclass.org",
    "ENABLE_OAUTH2_PROVIDER": true,
    "ENABLE_COURSE_DISCOVERY": true,
    "ENABLE_COURSEWARE_SEARCH": true,
    "ENABLE_DASHBOARD_SEARCH":  true,
    "ENABLE_EDXNOTES": true
  },
  "LMS_ROOT_URL": "http://hibbardsclass.org",
  "CMS_ROOT_URL": "http://studio.hibbardsclass.org",
  "CMS_BASE": "studio.hibbardsclass.org",
  "LMS_BASE": "hibbardsclass.org",
  "CONTACT_EMAIL": "rhibbard@nsd131.org",
  "CELERY_BROKER_HOSTNAME": "rabbitmq",
  "CELERY_BROKER_TRANSPORT": "amqp",
  "COMMENTS_SERVICE_URL": "http://forum:4567",
  "COMMENTS_SERVICE_KEY": "forumapikey",
  "MEDIA_ROOT": "/openedx/data/uploads/",
  "STATIC_ROOT_BASE": "/openedx/data/staticfiles",
  "ELASTIC_SEARCH_CONFIG": [{
    "host": "elasticsearch",
    "port": 9200
  }],
  "EMAIL_BACKEND": "django.core.mail.backends.smtp.EmailBackend",
  "EMAIL_HOST": "smtp",

  "EDXNOTES_PUBLIC_API": "http://notes.hibbardsclass.org/api/v1",
  "EDXNOTES_INTERNAL_API": "http://notes.hibbardsclass.org/api/v1",

  "JWT_AUTH": {
        "JWT_AUDIENCE": "SET-ME-PLEASE",
        "JWT_ISSUER": "http://hibbardsclass.org/oauth2",
        "JWT_SECRET_KEY": "SET-ME-PLEASE"
    },
    "JWT_EXPIRATION": 30,
    "JWT_EXPIRED_PRIVATE_SIGNING_KEYS": [],
    "JWT_ISSUER": "http://hibbardsclass.org/oauth2",
    "JWT_PRIVATE_SIGNING_KEY": null,

**Comment by regisb** [comment]
@roblhibbard please give the resut of `make info`. Also, what is the result of `docker ps | grep notes`?

**Comment by roblhibbard** [comment]
docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false
-------------------------
docker-compose --version
docker-compose version 1.23.1, build b02f1306

docker ps | grep notes   ---   result blank.

**Comment by roblhibbard** [comment]
sorry for the trouble, 

I needed to run a migration on notes. Which then made notes run and portainer that was also not working.

thank you for all your help

**Comment by roblhibbard** [comment]
ps. do you know of a way to set local storage for file uploads, the default goes to Amazon s3?

**Comment by regisb** [comment]
Ok I'll close this then.

As for your question about file uploads, do you mean peer-assessment file uploads? You might want to follow these instructions: https://github.com/edx/edx-ora2/blob/master/openassessment/fileupload/backends/filesystem.py#L11
