### ISSUE TITLE
Local filesystem storage for peer-assessment file uploads

### ISSUE THREAD

**Issue by roblhibbard** [regisb/openedx-docker#97]
Yes I did mean the peer-assessment file uploads. From my previous  #96 .

it looks like the  
<pre> url(r'^openassessment/storage', include(openassessment.fileupload.urls)), </pre>
is already included in the urls.py file.

Do I just need to add this below to the /config/openedx/lms.env.json file?

<pre>ORA2_FILEUPLOAD_CACHE_NAME = "ora2-storage"
        CACHES = {
            ...
            'ora2-storage': {
                'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
                ...
            },
            ...
        }
</pre>

thanks again,
Robert

**Comment by regisb** [comment]
These settings are required. Modify lms.env.json such that:

```
"CACHES": {
    ...
    "ora2-storage": {
      "KEY_PREFIX":  "ora2-storage",
      "BACKEND": "django.core.cache.backends.memcached.MemcachedCache",
      "KEY_FUNCTION": "util.memcache.safe_key",
      "LOCATION": "memcached:11211"
    },
    ...
}
```

Then, add to `config/openedx/lms/universal.py`:

```
ORA2_FILEUPLOAD_CACHE_NAME = "ora2-storage"
```

I think it makes sense to activate local filesystem storage by default for ora2 in openedx-docker, so I'm going to implement the feature and you won't have to make any change to the platform.

**Comment by roblhibbard** [comment]
config/openedx/lms/universal.py:  I don't have a universal.py file in this directory. 
I tried adding to production.py in /openedx-docker/config/openedx/universal/lms$ but had not success.

Maybe I am missing something, sorry for being such a noob.

Robert

**Comment by regisb** [comment]
I am currently in the process of activating the django backend for ORA2, but I'm facing errors:

```
Traceback (most recent call last):                                                                                                                            
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner                                                          
    response = get_response(request)                                                                                                                          
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response                                               
    response = self._get_response(request)                                                                                                                    
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response                                                      
    response = self.process_exception_by_middleware(e, request)                                                                                               
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response                                                      
    response = wrapped_callback(request, *callback_args, **callback_kwargs)                                                                                   
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 185, in inner                                                                
    return func(*args, **kwargs)                                                                                                                              
  File "/openedx/edx-platform/lms/djangoapps/courseware/module_render.py", line 962, in handle_xblock_callback                                                
    return _invoke_xblock_handler(request, course_id, usage_id, handler, suffix, course=course)                                                               
  File "/openedx/edx-platform/lms/djangoapps/courseware/module_render.py", line 1068, in _invoke_xblock_handler                                               
    resp = instance.handle(handler, req, suffix)                                                                                                              
  File "/usr/local/lib/python2.7/dist-packages/xblock/mixins.py", line 90, in handle                                                                          
    return self.runtime.handle(self, handler_name, request, suffix)                                                                                           
  File "/openedx/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1347, in handle                                                                   
    return super(MetricsMixin, self).handle(block, handler_name, request, suffix=suffix)                                                                      
  File "/usr/local/lib/python2.7/dist-packages/xblock/runtime.py", line 1037, in handle                                                                       
    results = handler(request, suffix)                                                                                                                        
  File "/usr/local/lib/python2.7/dist-packages/xblock/mixins.py", line 74, in wrapper                                                                         
    response = json.dumps(response)                                                                                                                           
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps                                                                                              
    return _default_encoder.encode(obj)    
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: u'/openassessment/fileupload/django/4dd623a62f4e626d827277cd3fedaf45/course-v1:org+video1+01/block-v1:org+video1+01+type@openassessment+block@25d85
51f741342ac919590db2e72091b/' is not JSON serializable
```

This seems due to the fact that `json.dumps` cannot process urls which are the result of `django.core.urlresolvers.reverse`. I need to investigate this further and possibly fix this upstream.

**Comment by roblhibbard** [comment]
Thanks for the update, 
I tried multiple ways of implementing the 
<pre> ORA2_FILEUPLOAD_CACHE_NAME = "ora2-storage" </pre>
but could not get it to work. I was not sure which file to add it to so I tried multiple ones without success.

good luck with the other.

**Comment by regisb** [comment]
Bug report was opened upstream: https://github.com/edx/edx-ora2/issues/1139

**Comment by regisb** [comment]
This is now solved in the latest release. Please run:

```
git pull
make update
make configure
```

And then restart the lms/cms:

    make restart-openedx

**Comment by roblhibbard** [comment]
Did I do something wrong? I am getting this error now.

<pre>
lms_1_cb2e1b92e412 | 2018-11-25 16:23:52,500 INFO 12 [tracking] logger.py:50 - {"username": "robert", "event_type": "/courses/course-v1:CHS+FP101+2018_S1/xblock/block-v1:CHS+FP101+2018_S1+type@openassessment+block@f0e6e85787104ea98290adebf0c665bb/handler/upload_url", "ip": "184.155.240.3", "agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36", "host": "hibbardsclass.org", "referer": "http://hibbardsclass.org/courses/course-v1:CHS+FP101+2018_S1/courseware/ca878038c19741b690be4959d62f0ce8/c42bccaf3da648e2a49af1505a4d790d/1?activate_block_id=block-v1%3ACHS%2BFP101%2B2018_S1%2Btype%40vertical%2Bblock%400274ec1b1e83495a87eebaf4e1c6c61b", "accept_language": "en-US,en;q=0.9", "event": "{\"POST\": {}, \"GET\": {}}", "event_source": "server", "context": {"course_user_tags": {}, "user_id": 3, "org_id": "CHS", "course_id": "course-v1:CHS+FP101+2018_S1", "path": "/courses/course-v1:CHS+FP101+2018_S1/xblock/block-v1:CHS+FP101+2018_S1+type@openassessment+block@f0e6e85787104ea98290adebf0c665bb/handler/upload_url"}, "time": "2018-11-25T16:23:52.500465+00:00", "page": null}
lms_1_cb2e1b92e412 | 2018-11-25 16:23:52,562 ERROR 12 [courseware.module_render] module_render.py:1092 - error executing xblock handler
lms_1_cb2e1b92e412 | Traceback (most recent call last):
lms_1_cb2e1b92e412 |   File "/openedx/edx-platform/lms/djangoapps/courseware/module_render.py", line 1067, in _invoke_xblock_handler
lms_1_cb2e1b92e412 |     resp = instance.handle(handler, req, suffix)
lms_1_cb2e1b92e412 |   File "/usr/local/lib/python2.7/dist-packages/xblock/mixins.py", line 89, in handle
lms_1_cb2e1b92e412 |     return self.runtime.handle(self, handler_name, request, suffix)
lms_1_cb2e1b92e412 |   File "/openedx/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1347, in handle
lms_1_cb2e1b92e412 |     return super(MetricsMixin, self).handle(block, handler_name, request, suffix=suffix)
lms_1_cb2e1b92e412 |   File "/usr/local/lib/python2.7/dist-packages/xblock/runtime.py", line 1037, in handle
lms_1_cb2e1b92e412 |     results = handler(request, suffix)
lms_1_cb2e1b92e412 |   File "/usr/local/lib/python2.7/dist-packages/xblock/mixins.py", line 74, in wrapper
lms_1_cb2e1b92e412 |     return Response(json.dumps(response), content_type='application/json', charset='utf8')
lms_1_cb2e1b92e412 |   File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
lms_1_cb2e1b92e412 |     return _default_encoder.encode(obj)
lms_1_cb2e1b92e412 |   File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
lms_1_cb2e1b92e412 |     chunks = self.iterencode(o, _one_shot=True)
lms_1_cb2e1b92e412 |   File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
lms_1_cb2e1b92e412 |     return _iterencode(o, 0)
lms_1_cb2e1b92e412 |   File "/usr/lib/python2.7/json/encoder.py", line 184, in default
lms_1_cb2e1b92e412 |     raise TypeError(repr(o) + " is not JSON serializable")
lms_1_cb2e1b92e412 | TypeError: u'/openassessment/fileupload/submissions_attachments/d0f471de0adcf19e0c1972cf4420974f/course-v1:CHS+FP101+2018_S1/block-v1:CHS+FP101+2018_S1+type@openassessment+block@f0e6e85787104ea98290adebf0c665bb/' is not JSON serializable
lms_1_cb2e1b92e412 | 2018-11-25 16:23:52,565 ERROR 12 [root] signals.py:17 - Uncaught exception from None
lms_1_cb2e1b92e412 | Traceback (most recent call last):
lms_1_cb2e1b92e412 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
lms_1_cb2e1b92e412 |     response = get_response(request)
lms_1_cb2e1b92e412 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
lms_1_cb2e1b92e412 |     response = self._get_response(request)
lms_1_cb2e1b92e412 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
lms_1_cb2e1b92e412 |     response = self.process_exception_by_middleware(e, request)
lms_1_cb2e1b92e412 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
lms_1_cb2e1b92e412 |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
lms_1_cb2e1b92e412 |   File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 185, in inner
lms_1_cb2e1b92e412 |     return func(*args, **kwargs)
lms_1_cb2e1b92e412 |   File "/openedx/edx-platform/lms/djangoapps/courseware/module_render.py", line 962, in handle_xblock_callback
lms_1_cb2e1b92e412 |     return _invoke_xblock_handler(request, course_id, usage_id, handler, suffix, course=course)
lms_1_cb2e1b92e412 |   File "/openedx/edx-platform/lms/djangoapps/courseware/module_render.py", line 1067, in _invoke_xblock_handler
lms_1_cb2e1b92e412 |     resp = instance.handle(handler, req, suffix)
lms_1_cb2e1b92e412 |   File "/usr/local/lib/python2.7/dist-packages/xblock/mixins.py", line 89, in handle
lms_1_cb2e1b92e412 |     return self.runtime.handle(self, handler_name, request, suffix)
lms_1_cb2e1b92e412 |   File "/openedx/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1347, in handle
lms_1_cb2e1b92e412 |     return super(MetricsMixin, self).handle(block, handler_name, request, suffix=suffix)
lms_1_cb2e1b92e412 |   File "/usr/local/lib/python2.7/dist-packages/xblock/runtime.py", line 1037, in handle
lms_1_cb2e1b92e412 |     results = handler(request, suffix)
lms_1_cb2e1b92e412 |   File "/usr/local/lib/python2.7/dist-packages/xblock/mixins.py", line 74, in wrapper
lms_1_cb2e1b92e412 |     return Response(json.dumps(response), content_type='application/json', charset='utf8')
lms_1_cb2e1b92e412 |   File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
lms_1_cb2e1b92e412 |     return _default_encoder.encode(obj)
lms_1_cb2e1b92e412 |   File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
lms_1_cb2e1b92e412 |     chunks = self.iterencode(o, _one_shot=True)
lms_1_cb2e1b92e412 |   File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
lms_1_cb2e1b92e412 |     return _iterencode(o, 0)
lms_1_cb2e1b92e412 |   File "/usr/lib/python2.7/json/encoder.py", line 184, in default
lms_1_cb2e1b92e412 |     raise TypeError(repr(o) + " is not JSON serializable")
lms_1_cb2e1b92e412 | TypeError: u'/openassessment/fileupload/submissions_attachments/d0f471de0adcf19e0c1972cf4420974f/course-v1:CHS+FP101+2018_S1/block-v1:CHS+FP101+2018_S1+type@openassessment+block@f0e6e85787104ea98290adebf0c665bb/' is not JSON serializable
lms_1_cb2e1b92e412 | 2018-11-25 16:23:52,567 ERROR 12 [django.request] exception.py:135 - Internal Server Error: /courses/course-v1:CHS+FP101+2018_S1/xblock/block-v1:CHS+FP101+2018_S1+type@openassessment+block@f0e6e85787104ea98290adebf0c665bb/handler/upload_url
lms_1_cb2e1b92e412 | Traceback (most recent call last):
lms_1_cb2e1b92e412 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
lms_1_cb2e1b92e412 |     response = get_response(request)
lms_1_cb2e1b92e412 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
lms_1_cb2e1b92e412 |     response = self._get_response(request)
lms_1_cb2e1b92e412 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
lms_1_cb2e1b92e412 |     response = self.process_exception_by_middleware(e, request)
lms_1_cb2e1b92e412 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
lms_1_cb2e1b92e412 |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
lms_1_cb2e1b92e412 |   File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 185, in inner
lms_1_cb2e1b92e412 |     return func(*args, **kwargs)
lms_1_cb2e1b92e412 |   File "/openedx/edx-platform/lms/djangoapps/courseware/module_render.py", line 962, in handle_xblock_callback
lms_1_cb2e1b92e412 |     return _invoke_xblock_handler(request, course_id, usage_id, handler, suffix, course=course)
lms_1_cb2e1b92e412 |   File "/openedx/edx-platform/lms/djangoapps/courseware/module_render.py", line 1067, in _invoke_xblock_handler
lms_1_cb2e1b92e412 |     resp = instance.handle(handler, req, suffix)
lms_1_cb2e1b92e412 |   File "/usr/local/lib/python2.7/dist-packages/xblock/mixins.py", line 89, in handle
lms_1_cb2e1b92e412 |     return self.runtime.handle(self, handler_name, request, suffix)
lms_1_cb2e1b92e412 |   File "/openedx/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1347, in handle
lms_1_cb2e1b92e412 |     return super(MetricsMixin, self).handle(block, handler_name, request, suffix=suffix)
lms_1_cb2e1b92e412 |   File "/usr/local/lib/python2.7/dist-packages/xblock/runtime.py", line 1037, in handle
lms_1_cb2e1b92e412 |     results = handler(request, suffix)
lms_1_cb2e1b92e412 |   File "/usr/local/lib/python2.7/dist-packages/xblock/mixins.py", line 74, in wrapper
lms_1_cb2e1b92e412 |     return Response(json.dumps(response), content_type='application/json', charset='utf8')
lms_1_cb2e1b92e412 |   File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
lms_1_cb2e1b92e412 |     return _default_encoder.encode(obj)
lms_1_cb2e1b92e412 |   File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
lms_1_cb2e1b92e412 |     chunks = self.iterencode(o, _one_shot=True)
lms_1_cb2e1b92e412 |   File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
lms_1_cb2e1b92e412 |     return _iterencode(o, 0)
lms_1_cb2e1b92e412 |   File "/usr/lib/python2.7/json/encoder.py", line 184, in default
lms_1_cb2e1b92e412 |     raise TypeError(repr(o) + " is not JSON serializable")
lms_1_cb2e1b92e412 | TypeError: u'/openassessment/fileupload/submissions_attachments/d0f471de0adcf19e0c1972cf4420974f/course-v1:CHS+FP101+2018_S1/block-v1:CHS+FP101+2018_S1+type@openassessment+block@f0e6e85787104ea98290adebf0c665bb/' is not JSON serializable
</pre>

sorry for the trouble,

thank you again for your hard work.

**Comment by regisb** [comment]
You didn't do anything wrong, but I have issues pushing to Docker Hub. You will need to build the open edx image yourself. Please run:

    make build-openedx

Then:

    make restart-openedx

**Comment by roblhibbard** [comment]
Same issue after performing above items. 
make info listed below just in case.

<pre>Linux hibbsedxbox 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
-------------------------
git rev-parse HEAD
c9d1db1447cd2abc67e98c69481d0d912a8c5214
-------------------------
docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false
-------------------------
docker-compose --version
docker-compose version 1.23.1, build b02f1306
-------------------------
echo $EDX_PLATFORM_PATH

echo $EDX_PLATFORM_SETTINGS
</pre>

**Comment by regisb** [comment]
Just to be sure, can you try `make stop`, and then `make run`?

**Comment by roblhibbard** [comment]
Already tried that,
Thank you.

**Comment by roblhibbard** [comment]
Awesome,

it is working now,

thank you,
